import { defineTradeQuestions } from "../builder";

export const BATHROOM_RENOVATION_QUESTIONS = defineTradeQuestions("bathroom_renovation", [
  {
    id: "bathroom_renovation_scope",
    category: "project_size",
    priority: "very_high",
    question: "What is the scope of your bathroom renovation?",
    questionType: "multiple_choice",
    choices: ["Cosmetic refresh", "Partial remodel", "Full gut renovation", "Fixture swap only", "Not sure"],
    requiredInformation: "Bathroom renovation scope level",
    tags: ["scope", "type"],
  },
  {
    id: "bathroom_renovation_count",
    category: "project_size",
    priority: "very_high",
    question: "How many bathrooms are being renovated?",
    questionType: "multiple_choice",
    choices: ["1", "2", "3+", "Powder room only"],
    requiredInformation: "Number of bathrooms in scope",
    tags: ["count", "scope"],
  },
  {
    id: "bathroom_renovation_size",
    category: "project_size",
    priority: "very_high",
    question: "Approximate bathroom size?",
    questionType: "multiple_choice",
    choices: ["Small (under 40 sq ft)", "Medium (40–80 sq ft)", "Large (80–120 sq ft)", "Master suite (120+ sq ft)", "Not sure"],
    requiredInformation: "Bathroom square footage",
    tags: ["size", "sqft"],
  },
  {
    id: "bathroom_renovation_layout_change",
    category: "project_size",
    priority: "high",
    question: "Are you changing the bathroom layout?",
    questionType: "multiple_choice",
    choices: ["No — same layout", "Minor changes", "Major layout change", "Expand bathroom footprint", "Not sure"],
    requiredInformation: "Layout change scope",
    tags: ["layout", "structural"],
  },
  {
    id: "bathroom_renovation_type",
    category: "project_size",
    priority: "high",
    question: "What type of bathroom is this?",
    questionType: "multiple_choice",
    choices: ["Master bathroom", "Guest bathroom", "Kids bathroom", "Powder room", "Ensuite", "Other"],
    requiredInformation: "Bathroom type and use case",
    tags: ["type", "room"],
  },
  {
    id: "bathroom_renovation_components",
    category: "project_size",
    priority: "medium",
    question: "Which components are included?",
    questionType: "checkbox",
    choices: ["Vanity", "Toilet", "Shower", "Tub", "Tile work", "Flooring", "Plumbing", "Electrical", "Ventilation", "Other"],
    requiredInformation: "Renovation components in scope",
    tags: ["components", "scope"],
  },
  {
    id: "bathroom_renovation_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current condition of the bathroom?",
    questionType: "multiple_choice",
    choices: ["Good — cosmetic updates only", "Fair — some fixtures need replacing", "Poor — full renovation needed", "Not sure"],
    requiredInformation: "Current bathroom condition",
    tags: ["condition", "existing"],
  },
  {
    id: "bathroom_renovation_water_damage",
    category: "existing_conditions",
    priority: "very_high",
    question: "Is there water damage, mold, or mildew?",
    questionType: "multiple_choice",
    choices: ["No", "Minor", "Moderate", "Significant", "Not sure"],
    requiredInformation: "Water damage and mold extent",
    tags: ["water_damage", "mold"],
  },
  {
    id: "bathroom_renovation_plumbing_relocation",
    category: "existing_conditions",
    priority: "high",
    question: "Will plumbing need to be relocated?",
    questionType: "multiple_choice",
    choices: ["No relocation", "Minor adjustments", "Major relocation", "Not sure"],
    requiredInformation: "Plumbing relocation needs",
    tags: ["plumbing", "relocation"],
  },
  {
    id: "bathroom_renovation_subfloor",
    category: "existing_conditions",
    priority: "high",
    question: "Do you suspect subfloor damage under tile or flooring?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Possible soft spots", "Known damage", "Not sure"],
    requiredInformation: "Subfloor damage concerns",
    tags: ["subfloor", "damage"],
  },
  {
    id: "bathroom_renovation_ventilation",
    category: "existing_conditions",
    priority: "medium",
    question: "Does the bathroom have adequate ventilation?",
    questionType: "multiple_choice",
    choices: ["Yes — working fan", "Fan exists but weak", "No fan or window", "Not sure"],
    requiredInformation: "Current ventilation status",
    tags: ["ventilation", "fan"],
  },
  {
    id: "bathroom_renovation_wall_type",
    category: "existing_conditions",
    priority: "medium",
    question: "Are bathroom walls tile, drywall, or other?",
    questionType: "multiple_choice",
    choices: ["Full tile", "Partial tile", "Drywall only", "Mixed", "Not sure"],
    requiredInformation: "Existing wall construction type",
    tags: ["walls", "construction"],
  },
  {
    id: "bathroom_renovation_shower_tub",
    category: "materials",
    priority: "very_high",
    question: "What shower or tub setup do you want?",
    questionType: "multiple_choice",
    choices: ["Tub only", "Shower only", "Tub/shower combo", "Walk-in shower", "Freestanding tub", "Tub and separate shower", "Not sure"],
    requiredInformation: "Shower and tub configuration",
    tags: ["shower", "tub", "layout"],
  },
  {
    id: "bathroom_renovation_tile_type",
    category: "materials",
    priority: "high",
    question: "What tile or wall finish do you prefer?",
    questionType: "multiple_choice",
    choices: ["Ceramic tile", "Porcelain tile", "Natural stone", "Large format tile", "Acrylic surround", "Not decided"],
    requiredInformation: "Tile and wall finish preference",
    tags: ["tile", "material"],
  },
  {
    id: "bathroom_renovation_vanity",
    category: "materials",
    priority: "high",
    question: "What type of vanity do you want?",
    questionType: "multiple_choice",
    choices: ["Single sink", "Double sink", "Floating vanity", "Pedestal sink", "Keep existing", "Not decided"],
    requiredInformation: "Vanity type preference",
    tags: ["vanity", "sink"],
  },
  {
    id: "bathroom_renovation_flooring",
    category: "materials",
    priority: "medium",
    question: "What flooring do you want?",
    questionType: "multiple_choice",
    choices: ["Tile", "LVP / vinyl", "Natural stone", "Keep existing", "Not decided"],
    requiredInformation: "Bathroom flooring preference",
    tags: ["flooring", "material"],
  },
  {
    id: "bathroom_renovation_fixtures_supplied",
    category: "materials",
    priority: "medium",
    question: "Will you supply fixtures and materials?",
    questionType: "multiple_choice",
    choices: ["I'll supply everything", "Contractor supplies all", "Mix — some supplied by me", "Not sure"],
    requiredInformation: "Fixture and material supply responsibility",
    tags: ["fixtures", "supply"],
  },
  {
    id: "bathroom_renovation_glass_enclosure",
    category: "special_features",
    priority: "medium",
    question: "What type of shower enclosure do you want?",
    questionType: "multiple_choice",
    choices: ["Framed glass", "Frameless glass", "Shower curtain", "Walk-in — no door", "Not applicable", "Not sure"],
    requiredInformation: "Shower enclosure preference",
    tags: ["glass", "enclosure"],
  },
  {
    id: "bathroom_renovation_heated_floor",
    category: "special_features",
    priority: "low",
    question: "Are you interested in heated floors?",
    questionType: "yes_no",
    requiredInformation: "Heated floor interest",
    tags: ["heated_floor", "luxury"],
  },
  {
    id: "bathroom_renovation_niche_features",
    category: "special_features",
    priority: "low",
    question: "Do you want shower niches, benches, or built-ins?",
    questionType: "checkbox",
    choices: ["Shower niche", "Shower bench", "Built-in shelving", "Grab bars", "None"],
    requiredInformation: "Shower niches and built-in features",
    tags: ["niche", "bench", "features"],
  },
  {
    id: "bathroom_renovation_lighting",
    category: "special_features",
    priority: "medium",
    question: "What lighting updates are planned?",
    questionType: "checkbox",
    choices: ["Vanity lights", "Recessed ceiling lights", "Shower light", "Exhaust fan with light", "No changes"],
    requiredInformation: "Bathroom lighting upgrade scope",
    tags: ["lighting"],
  },
  {
    id: "bathroom_renovation_accessibility",
    category: "special_features",
    priority: "low",
    question: "Are accessibility features needed?",
    questionType: "multiple_choice",
    choices: ["No", "Grab bars", "Curbless shower", "Wider doorway", "Multiple accessibility features"],
    requiredInformation: "Accessibility feature requirements",
    tags: ["accessibility", "ada"],
  },
  {
    id: "bathroom_renovation_demo",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle demolition and disposal?",
    questionType: "yes_no",
    requiredInformation: "Demolition and disposal responsibility",
    tags: ["demo", "disposal"],
  },
  {
    id: "bathroom_renovation_other_bathrooms",
    category: "access_removal",
    priority: "medium",
    question: "Will other bathrooms be available during the renovation?",
    questionType: "yes_no",
    requiredInformation: "Alternate bathroom availability during work",
    tags: ["access", "living"],
  },
  {
    id: "bathroom_renovation_permits",
    category: "access_removal",
    priority: "medium",
    question: "Should the contractor handle permits?",
    questionType: "multiple_choice",
    choices: ["Yes", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling preference",
    tags: ["permits"],
  },
  {
    id: "bathroom_renovation_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like the renovation to start?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 1 month", "Within 2–3 months", "Within 6 months", "Flexible"],
    requiredInformation: "Desired project start date",
    tags: ["timeline", "start"],
  },
  {
    id: "bathroom_renovation_deadline",
    category: "timeline",
    priority: "medium",
    question: "Do you have a completion deadline?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — event or guest visit", "Yes — move-in date", "Yes — selling home", "Other"],
    requiredInformation: "Completion deadline",
    tags: ["deadline", "timeline"],
  },
  {
    id: "bathroom_renovation_design_help",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you need design assistance?",
    questionType: "multiple_choice",
    choices: ["Yes — full design help", "Some guidance needed", "I have a complete design", "Working with a designer"],
    requiredInformation: "Design assistance needs",
    tags: ["design", "preferences"],
  },
  {
    id: "bathroom_renovation_style",
    category: "customer_preferences",
    priority: "medium",
    question: "What bathroom style are you going for?",
    questionType: "multiple_choice",
    choices: ["Modern", "Traditional", "Spa-like", "Farmhouse", "Minimalist", "Not decided"],
    requiredInformation: "Bathroom design style preference",
    tags: ["style", "aesthetics"],
  },
  {
    id: "bathroom_renovation_quality_tier",
    category: "customer_preferences",
    priority: "medium",
    question: "What quality level are you targeting?",
    questionType: "multiple_choice",
    choices: ["Builder grade", "Mid-range", "High-end", "Luxury", "Contractor to advise"],
    requiredInformation: "Quality tier preference",
    tags: ["quality", "tier"],
  },
  {
    id: "bathroom_renovation_occupied",
    category: "customer_preferences",
    priority: "low",
    question: "Will you be living in the home during renovation?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during renovation",
    tags: ["occupied", "living"],
  },
  {
    id: "bathroom_renovation_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other bathroom renovation quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "bathroom_renovation_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is a workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "bathroom_renovation_home_age",
    category: "existing_conditions",
    priority: "medium",
    question: "Approximately how old is the home?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–30 years", "30–50 years", "Over 50 years", "Not sure"],
    requiredInformation: "Home age affecting renovation complexity",
    tags: ["age", "home"],
  },
  {
    id: "bathroom_renovation_toilet_type",
    category: "materials",
    priority: "low",
    question: "What type of toilet do you prefer?",
    questionType: "multiple_choice",
    choices: ["Standard height", "Comfort height", "Wall-mounted", "Keep existing", "Contractor to advise"],
    requiredInformation: "Toilet type preference",
    tags: ["toilet", "fixtures"],
  },
]);
