import { defineTradeQuestions } from "../builder";

export const CONCRETE_QUESTIONS = defineTradeQuestions("concrete", [
  {
    id: "concrete_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of concrete work do you need?",
    questionType: "multiple_choice",
    choices: ["New pour", "Replacement", "Repair", "Resurface / overlay", "Decorative concrete", "Multiple items"],
    requiredInformation: "Primary concrete project type",
    tags: ["scope", "type"],
  },
  {
    id: "concrete_application",
    category: "project_size",
    priority: "very_high",
    question: "What will the concrete be used for?",
    questionType: "checkbox",
    choices: ["Driveway", "Patio", "Sidewalk / walkway", "Garage floor", "Foundation", "Retaining wall", "Steps", "Other"],
    requiredInformation: "Concrete application type",
    tags: ["application", "scope"],
  },
  {
    id: "concrete_square_footage",
    category: "project_size",
    priority: "very_high",
    question: "Approximate square footage?",
    questionType: "multiple_choice",
    choices: ["Under 100 sq ft", "100–300 sq ft", "300–600 sq ft", "600–1,200 sq ft", "Over 1,200 sq ft", "Not sure"],
    requiredInformation: "Approximate concrete area",
    tags: ["size", "sqft"],
  },
  {
    id: "concrete_thickness",
    category: "project_size",
    priority: "high",
    question: "What thickness is needed?",
    questionType: "multiple_choice",
    choices: ["4 inches (standard)", "5–6 inches (heavy duty)", "Over 6 inches", "Contractor to advise", "Not sure"],
    requiredInformation: "Required concrete thickness",
    tags: ["thickness", "specs"],
  },
  {
    id: "concrete_shape",
    category: "project_size",
    priority: "medium",
    question: "What is the shape of the pour area?",
    questionType: "multiple_choice",
    choices: ["Rectangle", "L-shaped", "Curved or irregular", "Multiple sections", "Not sure"],
    requiredInformation: "Pour area shape and layout",
    tags: ["shape", "layout"],
  },
  {
    id: "concrete_linear_feet",
    category: "project_size",
    priority: "medium",
    question: "If a walkway or curb, approximate linear feet?",
    questionType: "multiple_choice",
    choices: ["Under 50 ft", "50–100 ft", "100–200 ft", "Over 200 ft", "Not applicable", "Not sure"],
    requiredInformation: "Linear footage for walkways or curbs",
    tags: ["linear", "walkway"],
  },
  {
    id: "concrete_existing_surface",
    category: "existing_conditions",
    priority: "very_high",
    question: "Is there existing concrete to remove or repair?",
    questionType: "multiple_choice",
    choices: ["No — new pour on bare ground", "Yes — remove and replace", "Yes — repair existing", "Yes — pour over existing", "Not sure"],
    requiredInformation: "Existing concrete situation",
    tags: ["existing", "removal"],
  },
  {
    id: "concrete_existing_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the condition of existing concrete?",
    questionType: "multiple_choice",
    choices: ["No existing concrete", "Minor cracks", "Moderate cracking or settling", "Severe damage — full replacement", "Not sure"],
    requiredInformation: "Existing concrete condition",
    tags: ["condition", "cracks"],
  },
  {
    id: "concrete_subgrade",
    category: "existing_conditions",
    priority: "high",
    question: "What is the ground condition under the pour area?",
    questionType: "multiple_choice",
    choices: ["Level and compacted", "Needs grading", "Soft or unstable soil", "Rocky", "Not sure"],
    requiredInformation: "Subgrade condition and prep needs",
    tags: ["subgrade", "soil"],
  },
  {
    id: "concrete_drainage",
    category: "existing_conditions",
    priority: "high",
    question: "Are there drainage or slope requirements?",
    questionType: "multiple_choice",
    choices: ["No special drainage", "Slope away from structure", "Drain channel needed", "Significant drainage issues", "Not sure"],
    requiredInformation: "Drainage and slope requirements",
    tags: ["drainage", "slope"],
  },
  {
    id: "concrete_reinforcement_existing",
    category: "existing_conditions",
    priority: "medium",
    question: "Does existing concrete have rebar or wire mesh?",
    questionType: "multiple_choice",
    choices: ["Not applicable — new pour", "Yes — rebar", "Yes — wire mesh", "Unknown", "No reinforcement"],
    requiredInformation: "Existing reinforcement type",
    tags: ["rebar", "reinforcement"],
  },
  {
    id: "concrete_finish_type",
    category: "materials",
    priority: "high",
    question: "What finish do you want?",
    questionType: "multiple_choice",
    choices: ["Broom finish", "Smooth trowel", "Exposed aggregate", "Stamped / decorative", "Polished", "Not sure"],
    requiredInformation: "Concrete finish preference",
    tags: ["finish", "texture"],
  },
  {
    id: "concrete_color",
    category: "materials",
    priority: "medium",
    question: "Do you want colored or stained concrete?",
    questionType: "multiple_choice",
    choices: ["Standard gray", "Integral color", "Stained", "Painted / coated", "Not sure"],
    requiredInformation: "Color or stain preference",
    tags: ["color", "stain"],
  },
  {
    id: "concrete_reinforcement",
    category: "materials",
    priority: "medium",
    question: "What reinforcement do you want?",
    questionType: "multiple_choice",
    choices: ["Wire mesh", "Rebar grid", "Fiber reinforcement", "Contractor to advise", "Not sure"],
    requiredInformation: "Reinforcement preference",
    tags: ["reinforcement", "rebar"],
  },
  {
    id: "concrete_mix_strength",
    category: "materials",
    priority: "low",
    question: "Do you have a specific concrete mix requirement?",
    questionType: "multiple_choice",
    choices: ["Standard mix", "High-strength mix", "Contractor to advise", "Not sure"],
    requiredInformation: "Concrete mix strength requirements",
    tags: ["mix", "strength"],
  },
  {
    id: "concrete_stamped_pattern",
    category: "special_features",
    priority: "medium",
    question: "If stamped, do you have a pattern preference?",
    questionType: "multiple_choice",
    choices: ["Slate / stone", "Brick", "Wood plank", "Tile", "Contractor to show options", "Not applicable"],
    requiredInformation: "Stamped concrete pattern preference",
    tags: ["stamped", "pattern"],
  },
  {
    id: "concrete_control_joints",
    category: "special_features",
    priority: "low",
    question: "Do you have preferences for control joint layout?",
    questionType: "multiple_choice",
    choices: ["Contractor standard layout", "Minimize visible joints", "Specific layout needed", "Not sure"],
    requiredInformation: "Control joint layout preference",
    tags: ["joints", "cracking"],
  },
  {
    id: "concrete_curbing",
    category: "special_features",
    priority: "low",
    question: "Is decorative curbing or edging needed?",
    questionType: "multiple_choice",
    choices: ["No", "Standard curb", "Decorative curb", "Not sure"],
    requiredInformation: "Curbing or edging scope",
    tags: ["curbing", "edging"],
  },
  {
    id: "concrete_steps",
    category: "special_features",
    priority: "medium",
    question: "Are concrete steps or stairs part of this project?",
    questionType: "multiple_choice",
    choices: ["No steps", "1–3 steps", "4+ steps", "Replace existing steps", "Not sure"],
    requiredInformation: "Concrete steps scope",
    tags: ["steps", "stairs"],
  },
  {
    id: "concrete_permits",
    category: "special_features",
    priority: "medium",
    question: "Should the contractor handle permits?",
    questionType: "multiple_choice",
    choices: ["Yes", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling preference",
    tags: ["permits"],
  },
  {
    id: "concrete_removal",
    category: "access_removal",
    priority: "very_high",
    question: "Should existing concrete be removed and disposed of?",
    questionType: "multiple_choice",
    choices: ["Yes — full removal", "Partial removal", "No removal needed", "Not sure"],
    requiredInformation: "Concrete removal and disposal scope",
    tags: ["removal", "demo"],
  },
  {
    id: "concrete_site_access",
    category: "access_removal",
    priority: "high",
    question: "Can a concrete truck access the pour site?",
    questionType: "multiple_choice",
    choices: ["Yes — direct truck access", "Pump truck needed", "Wheelbarrow / buggy only", "Not sure"],
    requiredInformation: "Concrete truck and equipment access",
    tags: ["access", "truck"],
  },
  {
    id: "concrete_obstacles",
    category: "access_removal",
    priority: "medium",
    question: "Are there obstacles near the work area (trees, fences, utilities)?",
    questionType: "multiple_choice",
    choices: ["No obstacles", "Minor obstacles", "Significant obstacles", "Not sure"],
    requiredInformation: "Site obstacles affecting pour",
    tags: ["obstacles", "access"],
  },
  {
    id: "concrete_utility_locates",
    category: "access_removal",
    priority: "medium",
    question: "Are underground utilities a concern?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Need utility locates", "Known utilities in area", "Not sure"],
    requiredInformation: "Underground utility concerns",
    tags: ["utilities", "underground"],
  },
  {
    id: "concrete_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like the work done?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 2 weeks", "Within 1 month", "This season", "Flexible"],
    requiredInformation: "Desired project timeframe",
    tags: ["timeline", "start"],
  },
  {
    id: "concrete_weather_constraint",
    category: "timeline",
    priority: "medium",
    question: "Are there weather constraints for the pour?",
    questionType: "multiple_choice",
    choices: ["No constraints", "Prefer warm weather", "Must complete before winter", "Flexible"],
    requiredInformation: "Weather constraints for concrete pour",
    tags: ["weather", "season"],
  },
  {
    id: "concrete_cure_time",
    category: "timeline",
    priority: "low",
    question: "Do you need the surface usable by a specific date?",
    questionType: "multiple_choice",
    choices: ["No rush", "Yes — need access within 1 week", "Yes — event or deadline", "Not sure"],
    requiredInformation: "Surface usability deadline",
    tags: ["cure", "deadline"],
  },
  {
    id: "concrete_sealing",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you want the concrete sealed or coated?",
    questionType: "multiple_choice",
    choices: ["No sealing", "Standard sealer", "Premium sealer", "Epoxy coating", "Not sure"],
    requiredInformation: "Sealing or coating preference",
    tags: ["sealer", "coating"],
  },
  {
    id: "concrete_heated",
    category: "customer_preferences",
    priority: "low",
    question: "Are you interested in heated concrete (driveway or patio)?",
    questionType: "yes_no",
    requiredInformation: "Heated concrete interest",
    tags: ["heated", "snow_melt"],
  },
  {
    id: "concrete_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other concrete quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "concrete_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is a workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "concrete_load_requirements",
    category: "existing_conditions",
    priority: "medium",
    question: "Will heavy vehicles park on this concrete?",
    questionType: "multiple_choice",
    choices: ["Foot traffic only", "Cars only", "Trucks or RVs", "Heavy equipment", "Not sure"],
    requiredInformation: "Load requirements for concrete design",
    tags: ["load", "vehicles"],
  },
  {
    id: "concrete_adjacent_structures",
    category: "existing_conditions",
    priority: "medium",
    question: "Is the pour adjacent to a foundation or structure?",
    questionType: "multiple_choice",
    choices: ["Yes — against house or garage", "Yes — retaining wall or structure", "Freestanding — no adjacent structure", "Not sure"],
    requiredInformation: "Adjacent structure considerations",
    tags: ["foundation", "adjacent"],
  },
  {
    id: "concrete_expansion_joints",
    category: "materials",
    priority: "low",
    question: "Are expansion joints needed against existing structures?",
    questionType: "multiple_choice",
    choices: ["Contractor to determine", "Yes — against house", "Not needed", "Not sure"],
    requiredInformation: "Expansion joint requirements",
    tags: ["expansion", "joints"],
  },
  {
    id: "concrete_landscaping_restore",
    category: "access_removal",
    priority: "low",
    question: "Will landscaping need to be restored after the pour?",
    questionType: "multiple_choice",
    choices: ["No landscaping nearby", "Minor restoration", "Significant restoration", "Not sure"],
    requiredInformation: "Landscaping restoration needs",
    tags: ["landscaping", "restoration"],
  },
]);
