import { defineTradeQuestions } from "../builder";

export const DECK_FENCE_QUESTIONS = defineTradeQuestions("deck_fence", [
  {
    id: "deck_fence_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of project is this?",
    questionType: "multiple_choice",
    choices: ["New deck", "Deck repair or resurface", "Deck replacement", "New fence", "Fence repair", "Both deck and fence"],
    requiredInformation: "Primary deck or fence project type",
    tags: ["scope", "type"],
  },
  {
    id: "deck_fence_deck_size",
    category: "project_size",
    priority: "very_high",
    question: "Approximately how large will the new deck be?",
    questionType: "multiple_choice",
    choices: ["Under 100 sq ft", "100–200 sq ft", "200–400 sq ft", "Over 400 sq ft", "Not sure"],
    requiredInformation: "Approximate new deck size",
    tags: ["deck", "size"],
  },
  {
    id: "deck_fence_deck_height",
    category: "project_size",
    priority: "high",
    question: "How high will the deck be off the ground?",
    questionType: "multiple_choice",
    choices: ["Ground level (under 2 ft)", "Low (2–4 ft)", "Mid (4–8 ft)", "High (8+ ft)", "Multi-level", "Not sure"],
    requiredInformation: "Deck height above ground",
    tags: ["deck", "height"],
  },
  {
    id: "deck_fence_fence_length",
    category: "project_size",
    priority: "high",
    question: "Approximately how many linear feet of fencing?",
    questionType: "multiple_choice",
    choices: ["Under 50 ft", "50–100 ft", "100–200 ft", "200–400 ft", "Over 400 ft", "Not applicable", "Not sure"],
    requiredInformation: "Approximate fence linear footage",
    tags: ["fence", "length"],
  },
  {
    id: "deck_fence_fence_height",
    category: "project_size",
    priority: "high",
    question: "What fence height do you need?",
    questionType: "multiple_choice",
    choices: ["3–4 ft", "5–6 ft", "6–8 ft", "Varies by section", "Not applicable", "Not sure"],
    requiredInformation: "Desired fence height",
    tags: ["fence", "height"],
  },
  {
    id: "deck_fence_levels",
    category: "project_size",
    priority: "medium",
    question: "Will the deck have multiple levels?",
    questionType: "multiple_choice",
    choices: ["Single level", "Two levels", "Three or more", "Not applicable"],
    requiredInformation: "Number of deck levels",
    tags: ["deck", "levels"],
  },
  {
    id: "deck_fence_shape",
    category: "project_size",
    priority: "medium",
    question: "What shape is the deck?",
    questionType: "multiple_choice",
    choices: ["Rectangle", "L-shaped", "Wraparound", "Custom shape", "Not applicable", "Not sure"],
    requiredInformation: "Deck shape and layout",
    tags: ["deck", "layout"],
  },
  {
    id: "deck_fence_existing_deck",
    category: "existing_conditions",
    priority: "very_high",
    question: "Is there an existing deck or patio?",
    questionType: "multiple_choice",
    choices: ["No — new build", "Yes — deck exists", "Yes — patio exists", "Yes — both", "Not sure"],
    requiredInformation: "Existing deck or patio presence",
    tags: ["existing", "deck", "patio"],
  },
  {
    id: "deck_fence_removal",
    category: "existing_conditions",
    priority: "very_high",
    question: "Should the existing deck or patio be removed as part of this project?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Not sure"],
    requiredInformation: "Existing structure removal requirement",
    tags: ["removal", "demo"],
  },
  {
    id: "deck_fence_existing_condition",
    category: "existing_conditions",
    priority: "high",
    question: "What is the condition of the existing deck or fence?",
    questionType: "multiple_choice",
    choices: ["No existing structure", "Good — minor repairs", "Fair — moderate repairs", "Poor — needs replacement", "Not sure"],
    requiredInformation: "Existing structure condition",
    tags: ["condition", "existing"],
  },
  {
    id: "deck_fence_rotting_damage",
    category: "existing_conditions",
    priority: "high",
    question: "Is there visible rot, warping, or structural damage?",
    questionType: "multiple_choice",
    choices: ["No damage", "Surface wear only", "Some rot or warping", "Significant structural damage", "Not sure"],
    requiredInformation: "Rot and structural damage extent",
    tags: ["rot", "damage", "structural"],
  },
  {
    id: "deck_fence_foundation",
    category: "existing_conditions",
    priority: "high",
    question: "What is the ground condition where the deck or fence will go?",
    questionType: "multiple_choice",
    choices: ["Level and firm", "Slight slope", "Significant slope", "Rocky or uneven", "Not sure"],
    requiredInformation: "Ground and foundation conditions",
    tags: ["foundation", "ground"],
  },
  {
    id: "deck_fence_existing_posts",
    category: "existing_conditions",
    priority: "medium",
    question: "Can existing posts or footings be reused?",
    questionType: "multiple_choice",
    choices: ["Yes", "No — new footings needed", "Not sure", "Not applicable — new build"],
    requiredInformation: "Reusability of existing posts or footings",
    tags: ["posts", "footings"],
  },
  {
    id: "deck_fence_deck_material",
    category: "materials",
    priority: "very_high",
    question: "Which material would you prefer for your new deck?",
    questionType: "multiple_choice",
    choices: ["Composite", "Pressure-treated", "Cedar", "PVC", "I'm not sure"],
    requiredInformation: "Preferred deck material",
    tags: ["deck", "material"],
  },
  {
    id: "deck_fence_fence_material",
    category: "materials",
    priority: "high",
    question: "Which material do you prefer for fencing?",
    questionType: "multiple_choice",
    choices: ["Wood — cedar or pine", "Composite", "Vinyl / PVC", "Aluminum", "Chain link", "Contractor to advise", "Not applicable"],
    requiredInformation: "Preferred fence material",
    tags: ["fence", "material"],
  },
  {
    id: "deck_fence_railing_material",
    category: "materials",
    priority: "medium",
    question: "What railing material do you prefer?",
    questionType: "multiple_choice",
    choices: ["Match deck material", "Wood", "Composite", "Aluminum", "Cable railing", "Glass panels", "Not applicable"],
    requiredInformation: "Railing material preference",
    tags: ["railing", "material"],
  },
  {
    id: "deck_fence_stain_color",
    category: "materials",
    priority: "low",
    question: "Do you have a stain or color preference?",
    questionType: "multiple_choice",
    choices: ["Natural wood tone", "Dark stain", "Light stain", "Painted", "No preference", "Not applicable"],
    requiredInformation: "Stain or color preference",
    tags: ["stain", "color"],
  },
  {
    id: "deck_fence_inclusions",
    category: "special_features",
    priority: "very_high",
    question: "Which of these should be included?",
    questionType: "checkbox",
    choices: ["Stairs", "Railings", "Built-in seating", "Lighting", "Privacy screen", "Other", "None"],
    requiredInformation: "Deck features and inclusions",
    tags: ["features", "inclusions"],
  },
  {
    id: "deck_fence_gate_count",
    category: "special_features",
    priority: "medium",
    question: "How many fence gates are needed?",
    questionType: "multiple_choice",
    choices: ["None", "1 gate", "2 gates", "3+ gates", "Not applicable"],
    requiredInformation: "Number of fence gates",
    tags: ["gate", "fence"],
  },
  {
    id: "deck_fence_pergola",
    category: "special_features",
    priority: "medium",
    question: "Do you want a pergola, shade structure, or roof?",
    questionType: "multiple_choice",
    choices: ["No", "Pergola", "Shade sail", "Solid roof", "Not sure"],
    requiredInformation: "Shade structure preference",
    tags: ["pergola", "shade"],
  },
  {
    id: "deck_fence_underdeck",
    category: "special_features",
    priority: "low",
    question: "Is under-deck drainage or storage wanted?",
    questionType: "multiple_choice",
    choices: ["No", "Under-deck drainage system", "Enclosed storage", "Both", "Not sure"],
    requiredInformation: "Under-deck features",
    tags: ["underdeck", "drainage"],
  },
  {
    id: "deck_fence_hot_tub",
    category: "special_features",
    priority: "low",
    question: "Will the deck need to support a hot tub?",
    questionType: "yes_no",
    requiredInformation: "Hot tub load requirement",
    tags: ["hot_tub", "structural"],
  },
  {
    id: "deck_fence_permit",
    category: "special_features",
    priority: "medium",
    question: "Should the contractor handle permits?",
    questionType: "multiple_choice",
    choices: ["Yes", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling preference",
    tags: ["permits"],
  },
  {
    id: "deck_fence_site_access",
    category: "access_removal",
    priority: "high",
    question: "Is there clear access for materials and equipment?",
    questionType: "multiple_choice",
    choices: ["Yes — easy access", "Limited — narrow side yard", "Difficult — obstacles present", "Not sure"],
    requiredInformation: "Site access for materials delivery",
    tags: ["access", "delivery"],
  },
  {
    id: "deck_fence_demo_disposal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle demolition and debris removal?",
    questionType: "yes_no",
    requiredInformation: "Demolition and debris removal responsibility",
    tags: ["demo", "disposal"],
  },
  {
    id: "deck_fence_utilities",
    category: "access_removal",
    priority: "medium",
    question: "Are there underground utilities to consider?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Possible — need locates", "Known utilities in area", "Not sure"],
    requiredInformation: "Underground utility concerns",
    tags: ["utilities", "underground"],
  },
  {
    id: "deck_fence_landscaping",
    category: "access_removal",
    priority: "medium",
    question: "Will landscaping need to be disturbed or restored?",
    questionType: "multiple_choice",
    choices: ["No landscaping impact", "Minor disturbance", "Significant landscaping work", "Not sure"],
    requiredInformation: "Landscaping impact and restoration",
    tags: ["landscaping", "restoration"],
  },
  {
    id: "deck_fence_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like work to begin?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 1 month", "Within 2–3 months", "This season", "Flexible"],
    requiredInformation: "Desired project start date",
    tags: ["timeline", "start"],
  },
  {
    id: "deck_fence_completion_deadline",
    category: "timeline",
    priority: "medium",
    question: "Do you have a deadline for completion?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — event or season", "Yes — before selling home", "Other"],
    requiredInformation: "Completion deadline if any",
    tags: ["deadline", "timeline"],
  },
  {
    id: "deck_fence_weather_constraint",
    category: "timeline",
    priority: "medium",
    question: "Are there weather constraints for outdoor work?",
    questionType: "multiple_choice",
    choices: ["No constraints", "Prefer dry season", "Must finish before winter", "Flexible"],
    requiredInformation: "Weather constraints for construction",
    tags: ["weather", "season"],
  },
  {
    id: "deck_fence_hoa_approval",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you need HOA approval for this project?",
    questionType: "multiple_choice",
    choices: ["No HOA", "Yes — already approved", "Yes — need approval", "Not sure"],
    requiredInformation: "HOA approval status",
    tags: ["hoa", "approval"],
  },
  {
    id: "deck_fence_privacy_level",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is privacy for the fence or deck?",
    questionType: "multiple_choice",
    choices: ["Very important", "Somewhat", "Not a priority", "Not applicable"],
    requiredInformation: "Privacy priority",
    tags: ["privacy", "preferences"],
  },
  {
    id: "deck_fence_maintenance",
    category: "customer_preferences",
    priority: "low",
    question: "How important is low-maintenance material?",
    questionType: "multiple_choice",
    choices: ["Top priority", "Important", "Willing to maintain wood", "Not sure"],
    requiredInformation: "Low-maintenance material priority",
    tags: ["maintenance", "preferences"],
  },
  {
    id: "deck_fence_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is a workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "deck_fence_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other quotes for this project?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
]);
