import { defineTradeQuestions } from "../builder";

export const ELECTRICIAN_QUESTIONS = defineTradeQuestions("electrician", [
  {
    id: "electrician_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of electrical work do you need?",
    questionType: "multiple_choice",
    choices: ["Repair", "Upgrade", "New installation", "Panel upgrade", "Rewiring", "Inspection", "Multiple items"],
    requiredInformation: "Primary electrical project type",
    tags: ["scope", "type"],
  },
  {
    id: "electrician_scope_areas",
    category: "project_size",
    priority: "very_high",
    question: "Which areas are affected?",
    questionType: "checkbox",
    choices: ["Kitchen", "Bathroom", "Living areas", "Basement", "Garage", "Exterior", "Whole house", "Other"],
    requiredInformation: "Areas requiring electrical work",
    tags: ["locations", "scope"],
  },
  {
    id: "electrician_outlet_switch_count",
    category: "project_size",
    priority: "high",
    question: "How many outlets, switches, or fixtures are involved?",
    questionType: "multiple_choice",
    choices: ["1–2", "3–5", "6–10", "11–20", "20+", "Not sure"],
    requiredInformation: "Number of outlets, switches, or fixtures",
    tags: ["outlets", "fixtures", "count"],
  },
  {
    id: "electrician_panel_upgrade",
    category: "project_size",
    priority: "high",
    question: "Is a panel upgrade part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — upgrade existing panel", "Yes — new subpanel", "Not sure if needed"],
    requiredInformation: "Electrical panel upgrade scope",
    tags: ["panel", "upgrade"],
  },
  {
    id: "electrician_circuit_count",
    category: "project_size",
    priority: "medium",
    question: "How many new circuits are needed?",
    questionType: "multiple_choice",
    choices: ["None", "1–2", "3–5", "6+", "Not sure"],
    requiredInformation: "Number of new circuits required",
    tags: ["circuits", "scope"],
  },
  {
    id: "electrician_lighting_scope",
    category: "project_size",
    priority: "medium",
    question: "Is new lighting installation part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "Replace existing fixtures", "Add new fixtures", "Recessed lighting", "Landscape lighting", "Multiple types"],
    requiredInformation: "Lighting installation scope",
    tags: ["lighting", "fixtures"],
  },
  {
    id: "electrician_current_issue",
    category: "existing_conditions",
    priority: "very_high",
    question: "What electrical issue are you experiencing?",
    questionType: "checkbox",
    choices: ["No power", "Tripping breakers", "Flickering lights", "Burning smell", "Warm outlets", "Outdated wiring", "No issue — upgrade only", "Other"],
    requiredInformation: "Current electrical issues or symptoms",
    tags: ["issues", "symptoms"],
  },
  {
    id: "electrician_panel_age",
    category: "existing_conditions",
    priority: "very_high",
    question: "How old is your electrical panel?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–25 years", "25–40 years", "Over 40 years", "Not sure"],
    requiredInformation: "Electrical panel age",
    tags: ["panel", "age"],
  },
  {
    id: "electrician_panel_amperage",
    category: "existing_conditions",
    priority: "high",
    question: "Do you know your current panel amperage?",
    questionType: "multiple_choice",
    choices: ["60 amp", "100 amp", "150 amp", "200 amp", "400 amp", "Not sure"],
    requiredInformation: "Current panel amperage capacity",
    tags: ["panel", "amperage"],
  },
  {
    id: "electrician_wiring_type",
    category: "existing_conditions",
    priority: "high",
    question: "What type of wiring does your home have?",
    questionType: "multiple_choice",
    choices: ["Modern copper", "Aluminum wiring", "Knob and tube", "Mixed types", "Not sure"],
    requiredInformation: "Existing wiring type",
    tags: ["wiring", "type"],
  },
  {
    id: "electrician_home_age",
    category: "existing_conditions",
    priority: "high",
    question: "Approximately how old is the home?",
    questionType: "multiple_choice",
    choices: ["Under 20 years", "20–40 years", "40–60 years", "Over 60 years", "Not sure"],
    requiredInformation: "Home age affecting electrical systems",
    tags: ["age", "home"],
  },
  {
    id: "electrician_gfci_afci",
    category: "existing_conditions",
    priority: "medium",
    question: "Do you have GFCI and AFCI protection where required?",
    questionType: "multiple_choice",
    choices: ["Yes — up to code", "Partial protection", "No / outdated", "Not sure"],
    requiredInformation: "GFCI and AFCI protection status",
    tags: ["gfci", "afci", "code"],
  },
  {
    id: "electrician_previous_work",
    category: "existing_conditions",
    priority: "medium",
    question: "Has electrical work been done recently in this area?",
    questionType: "yes_no",
    requiredInformation: "Recent electrical work history",
    tags: ["history", "previous_work"],
  },
  {
    id: "electrician_fixture_supplied",
    category: "materials",
    priority: "high",
    question: "Will you supply fixtures or should the electrician?",
    questionType: "multiple_choice",
    choices: ["I'll supply fixtures", "Electrician supplies", "Mix", "Not applicable", "Not sure"],
    requiredInformation: "Fixture supply responsibility",
    tags: ["fixtures", "materials"],
  },
  {
    id: "electrician_outlet_type",
    category: "materials",
    priority: "medium",
    question: "What type of outlets do you need?",
    questionType: "checkbox",
    choices: ["Standard", "GFCI", "USB outlets", "240V / dryer", "EV charger outlet", "Outdoor rated", "Other"],
    requiredInformation: "Outlet types required",
    tags: ["outlets", "type"],
  },
  {
    id: "electrician_lighting_style",
    category: "materials",
    priority: "medium",
    question: "What lighting style are you considering?",
    questionType: "multiple_choice",
    choices: ["Recessed / can lights", "Pendant / chandelier", "Track lighting", "Under-cabinet", "Smart lighting", "Contractor to advise", "Not applicable"],
    requiredInformation: "Lighting style preference",
    tags: ["lighting", "style"],
  },
  {
    id: "electrician_smart_devices",
    category: "materials",
    priority: "low",
    question: "Do you want smart switches or dimmers?",
    questionType: "multiple_choice",
    choices: ["Yes — smart switches", "Yes — smart dimmers", "Standard switches", "Not applicable"],
    requiredInformation: "Smart switch or dimmer preference",
    tags: ["smart", "switches"],
  },
  {
    id: "electrician_ev_charger",
    category: "special_features",
    priority: "medium",
    question: "Is an EV charger installation part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — Level 1", "Yes — Level 2", "Yes — not sure which level", "Considering for future"],
    requiredInformation: "EV charger installation scope",
    tags: ["ev_charger", "installation"],
  },
  {
    id: "electrician_generator",
    category: "special_features",
    priority: "medium",
    question: "Is a generator or transfer switch involved?",
    questionType: "multiple_choice",
    choices: ["No", "Portable generator hookup", "Whole-home standby generator", "Transfer switch only", "Not sure"],
    requiredInformation: "Generator or transfer switch scope",
    tags: ["generator", "backup"],
  },
  {
    id: "electrician_ceiling_fan",
    category: "special_features",
    priority: "medium",
    question: "Are ceiling fans part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "1 fan", "2–3 fans", "4+ fans", "Replace existing fans"],
    requiredInformation: "Ceiling fan installation count",
    tags: ["ceiling_fan", "fixtures"],
  },
  {
    id: "electrician_surge_protection",
    category: "special_features",
    priority: "low",
    question: "Are you interested in whole-home surge protection?",
    questionType: "yes_no",
    requiredInformation: "Whole-home surge protection interest",
    tags: ["surge", "protection"],
  },
  {
    id: "electrician_permit",
    category: "special_features",
    priority: "medium",
    question: "Should the contractor handle permits and inspections?",
    questionType: "multiple_choice",
    choices: ["Yes — full handling", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling responsibility",
    tags: ["permits", "inspections"],
  },
  {
    id: "electrician_attic_access",
    category: "access_removal",
    priority: "high",
    question: "Is attic or crawlspace access available for wiring?",
    questionType: "multiple_choice",
    choices: ["Yes — easy access", "Limited access", "No access — walls must be opened", "Not applicable"],
    requiredInformation: "Attic or crawlspace access for wiring",
    tags: ["access", "attic"],
  },
  {
    id: "electrician_drywall_repair",
    category: "access_removal",
    priority: "medium",
    question: "Will drywall cutting or patching be needed?",
    questionType: "multiple_choice",
    choices: ["No", "Minor patching", "Significant drywall work", "Electrician handles patching", "I'll handle repairs"],
    requiredInformation: "Drywall access and repair scope",
    tags: ["drywall", "access"],
  },
  {
    id: "electrician_power_shutoff",
    category: "access_removal",
    priority: "medium",
    question: "Can power be shut off during work?",
    questionType: "multiple_choice",
    choices: ["Yes — full shutoff OK", "Partial shutoff only", "Must maintain power", "Not sure"],
    requiredInformation: "Power shutoff availability during work",
    tags: ["shutoff", "access"],
  },
  {
    id: "electrician_urgency",
    category: "timeline",
    priority: "very_high",
    question: "How urgent is this electrical work?",
    questionType: "multiple_choice",
    choices: ["Emergency — safety hazard", "Urgent — within a few days", "Soon — within 2 weeks", "Flexible — planning ahead"],
    requiredInformation: "Electrical work urgency",
    tags: ["urgency", "timeline"],
  },
  {
    id: "electrician_preferred_date",
    category: "timeline",
    priority: "high",
    question: "When would you like the work completed?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 1 week", "Within 2 weeks", "Within 1 month", "Flexible"],
    requiredInformation: "Preferred completion timeframe",
    tags: ["timeline", "schedule"],
  },
  {
    id: "electrician_availability",
    category: "timeline",
    priority: "medium",
    question: "When are you available for an on-site estimate?",
    questionType: "multiple_choice",
    choices: ["Weekday mornings", "Weekday afternoons", "Weekends", "Any time", "Flexible"],
    requiredInformation: "Customer availability for estimates",
    tags: ["availability", "estimate"],
  },
  {
    id: "electrician_code_compliance",
    category: "customer_preferences",
    priority: "high",
    question: "Is bringing electrical up to current code a priority?",
    questionType: "multiple_choice",
    choices: ["Yes — full code compliance", "Fix the issue only", "Contractor to advise"],
    requiredInformation: "Code compliance priority",
    tags: ["code", "compliance"],
  },
  {
    id: "electrician_licensed_insured",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you require a licensed and insured electrician?",
    questionType: "yes_no",
    requiredInformation: "Licensing and insurance requirement",
    tags: ["licensed", "insured"],
  },
  {
    id: "electrician_warranty",
    category: "customer_preferences",
    priority: "medium",
    question: "Is a workmanship warranty important to you?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "electrician_energy_efficiency",
    category: "customer_preferences",
    priority: "low",
    question: "Are you interested in energy-efficient lighting upgrades?",
    questionType: "yes_no",
    requiredInformation: "Energy-efficient lighting interest",
    tags: ["energy", "led"],
  },
  {
    id: "electrician_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other electrical quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "electrician_future_expansion",
    category: "customer_preferences",
    priority: "low",
    question: "Are you planning future electrical additions (solar, pool, workshop)?",
    questionType: "multiple_choice",
    choices: ["No future plans", "Yes — within 1–2 years", "Yes — long-term plans", "Not sure"],
    requiredInformation: "Future electrical expansion plans",
    tags: ["future", "expansion"],
  },
  {
    id: "electrician_home_occupied",
    category: "customer_preferences",
    priority: "low",
    question: "Will the home be occupied during the work?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during electrical work",
    tags: ["occupied", "access"],
  },
]);
