import { defineTradeQuestions } from "../builder";

export const FLOORING_QUESTIONS = defineTradeQuestions("flooring", [
  {
    id: "flooring_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of flooring project is this?",
    questionType: "multiple_choice",
    choices: ["New installation", "Replacement", "Repair", "Refinish existing", "Multiple areas"],
    requiredInformation: "Primary flooring project type",
    tags: ["scope", "type"],
  },
  {
    id: "flooring_room_count",
    category: "project_size",
    priority: "very_high",
    question: "How many rooms or areas need flooring?",
    questionType: "multiple_choice",
    choices: ["1 room", "2–3 rooms", "4–6 rooms", "7+ rooms", "Whole home"],
    requiredInformation: "Number of rooms or areas",
    tags: ["rooms", "scope"],
  },
  {
    id: "flooring_square_footage",
    category: "project_size",
    priority: "very_high",
    question: "Approximate square footage?",
    questionType: "multiple_choice",
    choices: ["Under 200 sq ft", "200–500 sq ft", "500–1,000 sq ft", "1,000–2,000 sq ft", "Over 2,000 sq ft", "Not sure"],
    requiredInformation: "Approximate flooring area",
    tags: ["size", "sqft"],
  },
  {
    id: "flooring_areas",
    category: "project_size",
    priority: "high",
    question: "Which areas need new flooring?",
    questionType: "checkbox",
    choices: ["Living room", "Kitchen", "Bedrooms", "Bathrooms", "Hallways", "Stairs", "Basement", "Other"],
    requiredInformation: "Specific areas for flooring",
    tags: ["areas", "locations"],
  },
  {
    id: "flooring_stairs",
    category: "project_size",
    priority: "medium",
    question: "Are stairs included in this project?",
    questionType: "multiple_choice",
    choices: ["No stairs", "1 flight", "2+ flights", "Stair refinish only"],
    requiredInformation: "Stair flooring scope",
    tags: ["stairs", "scope"],
  },
  {
    id: "flooring_subfloor_rooms",
    category: "project_size",
    priority: "medium",
    question: "Is this on a concrete slab or wood subfloor?",
    questionType: "multiple_choice",
    choices: ["Wood subfloor throughout", "Concrete slab throughout", "Mixed — both types", "Not sure"],
    requiredInformation: "Subfloor type across project areas",
    tags: ["subfloor", "type"],
  },
  {
    id: "flooring_current_type",
    category: "existing_conditions",
    priority: "very_high",
    question: "What flooring is currently installed?",
    questionType: "multiple_choice",
    choices: ["Carpet", "Hardwood", "Laminate", "Vinyl / LVP", "Tile", "Concrete", "Mixed types", "Not sure"],
    requiredInformation: "Current flooring material",
    tags: ["existing", "material"],
  },
  {
    id: "flooring_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the condition of the current flooring?",
    questionType: "multiple_choice",
    choices: ["Good — can stay as underlayment", "Fair — removal needed", "Poor — damaged subfloor suspected", "Not sure"],
    requiredInformation: "Current flooring condition",
    tags: ["condition", "existing"],
  },
  {
    id: "flooring_removal_needed",
    category: "existing_conditions",
    priority: "high",
    question: "Does existing flooring need to be removed?",
    questionType: "multiple_choice",
    choices: ["Yes — full removal", "Partial removal", "No — install over existing", "Not sure"],
    requiredInformation: "Existing floor removal requirement",
    tags: ["removal", "demo"],
  },
  {
    id: "flooring_subfloor_condition",
    category: "existing_conditions",
    priority: "high",
    question: "Do you know the subfloor condition?",
    questionType: "multiple_choice",
    choices: ["Good and level", "Minor repairs needed", "Significant leveling or repair needed", "Not sure"],
    requiredInformation: "Subfloor condition and leveling needs",
    tags: ["subfloor", "leveling"],
  },
  {
    id: "flooring_moisture_concerns",
    category: "existing_conditions",
    priority: "high",
    question: "Are there moisture concerns (basement, bathroom, slab)?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Minor moisture", "Known moisture issues", "Not sure"],
    requiredInformation: "Moisture concerns affecting flooring choice",
    tags: ["moisture", "basement"],
  },
  {
    id: "flooring_asbestos_concern",
    category: "existing_conditions",
    priority: "medium",
    question: "Is there old vinyl tile or flooring that may contain asbestos?",
    questionType: "multiple_choice",
    choices: ["No", "Possibly — home built before 1980", "Yes — known asbestos", "Not sure"],
    requiredInformation: "Asbestos flooring risk",
    tags: ["asbestos", "safety"],
  },
  {
    id: "flooring_new_material",
    category: "materials",
    priority: "very_high",
    question: "What type of flooring do you want?",
    questionType: "multiple_choice",
    choices: ["Hardwood", "Engineered hardwood", "Laminate", "Luxury vinyl plank (LVP)", "Tile", "Carpet", "Not decided"],
    requiredInformation: "Desired new flooring material",
    tags: ["material", "preference"],
  },
  {
    id: "flooring_hardwood_type",
    category: "materials",
    priority: "medium",
    question: "If hardwood, what type do you prefer?",
    questionType: "multiple_choice",
    choices: ["Solid hardwood", "Engineered hardwood", "Prefinished", "Site-finished", "Contractor to advise", "Not applicable"],
    requiredInformation: "Hardwood type preference",
    tags: ["hardwood", "type"],
  },
  {
    id: "flooring_tile_type",
    category: "materials",
    priority: "medium",
    question: "If tile, what type are you considering?",
    questionType: "multiple_choice",
    choices: ["Ceramic", "Porcelain", "Natural stone", "Large format", "Contractor to advise", "Not applicable"],
    requiredInformation: "Tile type preference",
    tags: ["tile", "type"],
  },
  {
    id: "flooring_material_supplied",
    category: "materials",
    priority: "medium",
    question: "Will you supply the flooring material?",
    questionType: "multiple_choice",
    choices: ["I'll supply materials", "Contractor supplies", "Not sure yet"],
    requiredInformation: "Material supply responsibility",
    tags: ["materials", "supply"],
  },
  {
    id: "flooring_underlayment",
    category: "materials",
    priority: "low",
    question: "Do you want upgraded underlayment or soundproofing?",
    questionType: "multiple_choice",
    choices: ["Standard underlayment", "Premium underlayment", "Soundproofing underlayment", "Contractor to advise", "Not sure"],
    requiredInformation: "Underlayment preference",
    tags: ["underlayment", "soundproofing"],
  },
  {
    id: "flooring_transitions",
    category: "special_features",
    priority: "medium",
    question: "Are transition strips or thresholds needed between rooms?",
    questionType: "multiple_choice",
    choices: ["Yes — multiple transitions", "A few transitions", "Not needed", "Not sure"],
    requiredInformation: "Transition strip requirements",
    tags: ["transitions", "thresholds"],
  },
  {
    id: "flooring_baseboards",
    category: "special_features",
    priority: "medium",
    question: "Are baseboards part of this project?",
    questionType: "multiple_choice",
    choices: ["No — keep existing", "Remove and reinstall existing", "Replace with new baseboards", "Add new baseboards", "Not sure"],
    requiredInformation: "Baseboard scope",
    tags: ["baseboards", "trim"],
  },
  {
    id: "flooring_radiant_heat",
    category: "special_features",
    priority: "low",
    question: "Is radiant floor heating involved?",
    questionType: "multiple_choice",
    choices: ["No", "Existing radiant heat", "Want to add radiant heat", "Not sure"],
    requiredInformation: "Radiant floor heating involvement",
    tags: ["radiant", "heating"],
  },
  {
    id: "flooring_pattern",
    category: "special_features",
    priority: "low",
    question: "Do you want a special pattern or layout?",
    questionType: "multiple_choice",
    choices: ["Standard layout", "Diagonal", "Herringbone", "Mixed-width planks", "Custom pattern", "Not sure"],
    requiredInformation: "Flooring pattern preference",
    tags: ["pattern", "layout"],
  },
  {
    id: "flooring_furniture_move",
    category: "access_removal",
    priority: "high",
    question: "Who will move furniture and appliances?",
    questionType: "multiple_choice",
    choices: ["Contractor handles all", "I'll move — contractor reinstalls", "I'll handle everything", "Not sure"],
    requiredInformation: "Furniture and appliance moving responsibility",
    tags: ["furniture", "access"],
  },
  {
    id: "flooring_debris_disposal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor remove and dispose of old flooring?",
    questionType: "yes_no",
    requiredInformation: "Old flooring disposal responsibility",
    tags: ["disposal", "removal"],
  },
  {
    id: "flooring_occupied",
    category: "access_removal",
    priority: "medium",
    question: "Will the home be occupied during installation?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during flooring work",
    tags: ["occupied", "access"],
  },
  {
    id: "flooring_room_clearance",
    category: "access_removal",
    priority: "medium",
    question: "Will rooms be completely cleared before work begins?",
    questionType: "multiple_choice",
    choices: ["Yes — fully cleared", "Partially cleared", "Need contractor to clear", "Not sure"],
    requiredInformation: "Room clearance status",
    tags: ["clearance", "prep"],
  },
  {
    id: "flooring_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like installation to begin?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 2 weeks", "Within 1 month", "Within 2–3 months", "Flexible"],
    requiredInformation: "Desired start date",
    tags: ["timeline", "start"],
  },
  {
    id: "flooring_duration_constraint",
    category: "timeline",
    priority: "medium",
    question: "Do you have a deadline for completion?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — move-in date", "Yes — event", "Yes — selling home", "Other"],
    requiredInformation: "Completion deadline",
    tags: ["deadline", "timeline"],
  },
  {
    id: "flooring_acclimation",
    category: "timeline",
    priority: "low",
    question: "Are you aware that some materials need acclimation time?",
    questionType: "multiple_choice",
    choices: ["Yes — flexible on timing", "Need fastest timeline", "Contractor to advise", "Not sure"],
    requiredInformation: "Acclimation timing flexibility",
    tags: ["acclimation", "timeline"],
  },
  {
    id: "flooring_color_style",
    category: "customer_preferences",
    priority: "medium",
    question: "Have you selected a color or style?",
    questionType: "multiple_choice",
    choices: ["Yes — selected", "Narrowed to options", "Need help choosing", "Contractor to advise"],
    requiredInformation: "Color and style selection status",
    tags: ["color", "style"],
  },
  {
    id: "flooring_durability",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is durability (pets, kids, high traffic)?",
    questionType: "multiple_choice",
    choices: ["Top priority", "Important", "Moderate", "Not a concern"],
    requiredInformation: "Durability requirements",
    tags: ["durability", "traffic"],
  },
  {
    id: "flooring_pets",
    category: "customer_preferences",
    priority: "low",
    question: "Do you have pets that affect flooring choice?",
    questionType: "multiple_choice",
    choices: ["No pets", "Dogs", "Cats", "Multiple pets"],
    requiredInformation: "Pet considerations for flooring",
    tags: ["pets", "durability"],
  },
  {
    id: "flooring_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is an installation warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Installation warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "flooring_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other flooring quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "flooring_samples",
    category: "customer_preferences",
    priority: "low",
    question: "Would you like to see material samples before deciding?",
    questionType: "yes_no",
    requiredInformation: "Interest in material samples",
    tags: ["samples", "selection"],
  },
  {
    id: "flooring_floor_level",
    category: "existing_conditions",
    priority: "medium",
    question: "What floor of the home is the work on?",
    questionType: "multiple_choice",
    choices: ["Main floor only", "Upper floor", "Basement", "Multiple floors"],
    requiredInformation: "Floor level of work areas",
    tags: ["floor_level", "location"],
  },
]);
