import { defineTradeQuestions } from "../builder";

export const GENERAL_RENOVATION_QUESTIONS = defineTradeQuestions("general_renovation", [
  {
    id: "general_renovation_scope",
    category: "project_size",
    priority: "very_high",
    question: "What is the overall scope of your renovation?",
    questionType: "multiple_choice",
    choices: ["Single room", "Multiple rooms", "Whole floor", "Whole home", "Addition", "Not sure"],
    requiredInformation: "Overall renovation scope",
    tags: ["scope", "size"],
  },
  {
    id: "general_renovation_square_footage",
    category: "project_size",
    priority: "very_high",
    question: "Approximate square footage affected?",
    questionType: "multiple_choice",
    choices: ["Under 200 sq ft", "200–500 sq ft", "500–1,500 sq ft", "1,500–3,000 sq ft", "Over 3,000 sq ft", "Not sure"],
    requiredInformation: "Renovation area square footage",
    tags: ["size", "sqft"],
  },
  {
    id: "general_renovation_rooms",
    category: "project_size",
    priority: "high",
    question: "Which rooms or areas are included?",
    questionType: "checkbox",
    choices: ["Kitchen", "Bathroom", "Bedrooms", "Living areas", "Basement", "Attic", "Garage", "Exterior", "Other"],
    requiredInformation: "Rooms and areas in renovation scope",
    tags: ["rooms", "areas"],
  },
  {
    id: "general_renovation_trades",
    category: "project_size",
    priority: "high",
    question: "Which trades are likely involved?",
    questionType: "checkbox",
    choices: ["Demolition", "Framing", "Plumbing", "Electrical", "HVAC", "Drywall", "Flooring", "Painting", "Carpentry", "Other"],
    requiredInformation: "Trades required for renovation",
    tags: ["trades", "scope"],
  },
  {
    id: "general_renovation_structural",
    category: "project_size",
    priority: "high",
    question: "Does the project involve structural changes?",
    questionType: "multiple_choice",
    choices: ["No structural changes", "Remove non-load-bearing walls", "Possible load-bearing wall removal", "Additions or extensions", "Not sure"],
    requiredInformation: "Structural change scope",
    tags: ["structural", "walls"],
  },
  {
    id: "general_renovation_levels",
    category: "project_size",
    priority: "medium",
    question: "How many floors are affected?",
    questionType: "multiple_choice",
    choices: ["1 floor", "2 floors", "3+ floors", "Basement included"],
    requiredInformation: "Number of floors in scope",
    tags: ["floors", "levels"],
  },
  {
    id: "general_renovation_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current condition of the space?",
    questionType: "multiple_choice",
    choices: ["Good — cosmetic updates", "Fair — moderate work needed", "Poor — major renovation required", "Gut to studs", "Not sure"],
    requiredInformation: "Current space condition",
    tags: ["condition", "existing"],
  },
  {
    id: "general_renovation_home_age",
    category: "existing_conditions",
    priority: "very_high",
    question: "Approximately how old is the home?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–30 years", "30–50 years", "Over 50 years", "Not sure"],
    requiredInformation: "Home age affecting renovation complexity",
    tags: ["age", "home"],
  },
  {
    id: "general_renovation_known_issues",
    category: "existing_conditions",
    priority: "high",
    question: "Are there known issues to address?",
    questionType: "checkbox",
    choices: ["Water damage", "Mold", "Foundation issues", "Outdated electrical", "Outdated plumbing", "Asbestos concern", "None known", "Other"],
    requiredInformation: "Known issues requiring remediation",
    tags: ["issues", "damage"],
  },
  {
    id: "general_renovation_layout_change",
    category: "existing_conditions",
    priority: "high",
    question: "Are you changing the floor plan or layout?",
    questionType: "multiple_choice",
    choices: ["No — same layout", "Minor adjustments", "Major reconfiguration", "Not sure"],
    requiredInformation: "Floor plan change scope",
    tags: ["layout", "floor_plan"],
  },
  {
    id: "general_renovation_permits_status",
    category: "existing_conditions",
    priority: "medium",
    question: "Do you know if permits will be required?",
    questionType: "multiple_choice",
    choices: ["Yes — permits needed", "Probably not", "Not sure"],
    requiredInformation: "Permit requirement awareness",
    tags: ["permits", "code"],
  },
  {
    id: "general_renovation_occupancy_type",
    category: "existing_conditions",
    priority: "medium",
    question: "Is this a primary residence, rental, or flip?",
    questionType: "multiple_choice",
    choices: ["Primary residence", "Rental property", "Flip / investment", "Vacation home", "Other"],
    requiredInformation: "Property use type",
    tags: ["property_type", "use"],
  },
  {
    id: "general_renovation_finish_level",
    category: "materials",
    priority: "high",
    question: "What finish level are you targeting?",
    questionType: "multiple_choice",
    choices: ["Builder grade", "Mid-range", "High-end", "Luxury", "Contractor to advise"],
    requiredInformation: "Finish quality tier",
    tags: ["quality", "finish"],
  },
  {
    id: "general_renovation_materials_supplied",
    category: "materials",
    priority: "medium",
    question: "Will you supply any materials or fixtures?",
    questionType: "multiple_choice",
    choices: ["Contractor supplies all", "I'll supply some materials", "I'll supply most materials", "Not sure yet"],
    requiredInformation: "Material supply responsibility",
    tags: ["materials", "supply"],
  },
  {
    id: "general_renovation_design_status",
    category: "materials",
    priority: "medium",
    question: "Do you have plans or designs ready?",
    questionType: "multiple_choice",
    choices: ["Yes — complete plans", "Partial plans", "Ideas only — need design help", "No plans yet"],
    requiredInformation: "Design and plan readiness",
    tags: ["plans", "design"],
  },
  {
    id: "general_renovation_flooring_plan",
    category: "materials",
    priority: "medium",
    question: "Is new flooring part of the renovation?",
    questionType: "multiple_choice",
    choices: ["No flooring changes", "Some rooms", "All affected areas", "Not decided"],
    requiredInformation: "Flooring scope in renovation",
    tags: ["flooring", "materials"],
  },
  {
    id: "general_renovation_custom_features",
    category: "special_features",
    priority: "medium",
    question: "Are there custom features or built-ins planned?",
    questionType: "checkbox",
    choices: ["Built-in shelving", "Custom cabinetry", "Fireplace", "Wet bar", "Home office built-ins", "None", "Other"],
    requiredInformation: "Custom features and built-ins",
    tags: ["custom", "built_ins"],
  },
  {
    id: "general_renovation_smart_home",
    category: "special_features",
    priority: "low",
    question: "Are smart home features part of the plan?",
    questionType: "multiple_choice",
    choices: ["No", "Basic smart features", "Full smart home integration", "Not sure"],
    requiredInformation: "Smart home feature scope",
    tags: ["smart_home", "technology"],
  },
  {
    id: "general_renovation_accessibility",
    category: "special_features",
    priority: "low",
    question: "Are accessibility modifications needed?",
    questionType: "multiple_choice",
    choices: ["No", "Minor modifications", "Significant accessibility upgrades", "Not sure"],
    requiredInformation: "Accessibility modification needs",
    tags: ["accessibility", "ada"],
  },
  {
    id: "general_renovation_energy_upgrades",
    category: "special_features",
    priority: "low",
    question: "Are energy efficiency upgrades part of the plan?",
    questionType: "multiple_choice",
    choices: ["No", "Insulation upgrades", "Window upgrades", "HVAC upgrade", "Multiple energy upgrades", "Not sure"],
    requiredInformation: "Energy efficiency upgrade scope",
    tags: ["energy", "efficiency"],
  },
  {
    id: "general_renovation_demo",
    category: "access_removal",
    priority: "very_high",
    question: "Should the contractor handle demolition?",
    questionType: "yes_no",
    requiredInformation: "Demolition responsibility",
    tags: ["demo", "removal"],
  },
  {
    id: "general_renovation_disposal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle debris removal and disposal?",
    questionType: "yes_no",
    requiredInformation: "Debris removal responsibility",
    tags: ["disposal", "debris"],
  },
  {
    id: "general_renovation_occupied",
    category: "access_removal",
    priority: "high",
    question: "Will you live in the home during renovation?",
    questionType: "multiple_choice",
    choices: ["Yes — staying during work", "No — moving out temporarily", "Partial occupancy", "Not sure"],
    requiredInformation: "Occupancy during renovation",
    tags: ["occupied", "living"],
  },
  {
    id: "general_renovation_site_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there adequate access for crews and materials?",
    questionType: "multiple_choice",
    choices: ["Yes", "Limited access", "Difficult access", "Not sure"],
    requiredInformation: "Site access for renovation work",
    tags: ["access", "delivery"],
  },
  {
    id: "general_renovation_storage",
    category: "access_removal",
    priority: "low",
    question: "Is on-site material storage available?",
    questionType: "multiple_choice",
    choices: ["Yes — garage or yard", "Limited storage", "No on-site storage", "Not sure"],
    requiredInformation: "On-site material storage availability",
    tags: ["storage", "materials"],
  },
  {
    id: "general_renovation_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like the renovation to start?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 1 month", "Within 2–3 months", "Within 6 months", "Flexible"],
    requiredInformation: "Desired project start date",
    tags: ["timeline", "start"],
  },
  {
    id: "general_renovation_deadline",
    category: "timeline",
    priority: "high",
    question: "Do you have a completion deadline?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — move-in date", "Yes — selling home", "Yes — event or holiday", "Other"],
    requiredInformation: "Completion deadline",
    tags: ["deadline", "timeline"],
  },
  {
    id: "general_renovation_phased",
    category: "timeline",
    priority: "medium",
    question: "Do you want the work done in phases?",
    questionType: "multiple_choice",
    choices: ["No — all at once", "Yes — phased by room", "Yes — phased by trade", "Not sure"],
    requiredInformation: "Phased construction preference",
    tags: ["phased", "schedule"],
  },
  {
    id: "general_renovation_gc_preference",
    category: "customer_preferences",
    priority: "very_high",
    question: "Do you want one contractor to manage the entire project?",
    questionType: "multiple_choice",
    choices: ["Yes — single general contractor", "I'll hire and coordinate trades", "Not sure"],
    requiredInformation: "General contractor preference",
    tags: ["gc", "coordination"],
  },
  {
    id: "general_renovation_design_help",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you need design or architectural help?",
    questionType: "multiple_choice",
    choices: ["Yes — full design services", "Some guidance", "I have an architect or designer", "No design help needed"],
    requiredInformation: "Design service needs",
    tags: ["design", "architect"],
  },
  {
    id: "general_renovation_style",
    category: "customer_preferences",
    priority: "medium",
    question: "What design style are you going for?",
    questionType: "multiple_choice",
    choices: ["Modern", "Traditional", "Farmhouse", "Industrial", "Transitional", "Not decided"],
    requiredInformation: "Design style preference",
    tags: ["style", "aesthetics"],
  },
  {
    id: "general_renovation_warranty",
    category: "customer_preferences",
    priority: "medium",
    question: "Is a workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "general_renovation_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other renovation quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "general_renovation_insurance",
    category: "customer_preferences",
    priority: "low",
    question: "Is this renovation related to an insurance claim?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — claim filed", "Yes — planning to file", "Not sure"],
    requiredInformation: "Insurance claim involvement",
    tags: ["insurance", "claim"],
  },
  {
    id: "general_renovation_hoa",
    category: "customer_preferences",
    priority: "low",
    question: "Are there HOA or building restrictions?",
    questionType: "multiple_choice",
    choices: ["No restrictions", "HOA approval needed", "Building code restrictions", "Not sure"],
    requiredInformation: "HOA or building restrictions",
    tags: ["hoa", "restrictions"],
  },
]);
