import { defineTradeQuestions } from "../builder";

export const HANDYMAN_QUESTIONS = defineTradeQuestions("handyman", [
  {
    id: "handyman_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of handyman work do you need?",
    questionType: "multiple_choice",
    choices: ["Single repair", "Multiple small tasks", "Assembly or installation", "Mounting / hanging", "Caulking / sealing", "General maintenance"],
    requiredInformation: "Primary handyman project type",
    tags: ["scope", "type"],
  },
  {
    id: "handyman_task_count",
    category: "project_size",
    priority: "very_high",
    question: "How many tasks or items are on your list?",
    questionType: "multiple_choice",
    choices: ["1 task", "2–3 tasks", "4–6 tasks", "7–10 tasks", "10+ tasks"],
    requiredInformation: "Number of tasks in scope",
    tags: ["tasks", "count"],
  },
  {
    id: "handyman_task_categories",
    category: "project_size",
    priority: "high",
    question: "What categories of work are involved?",
    questionType: "checkbox",
    choices: ["Drywall repair", "Painting touch-up", "Carpentry", "Plumbing minor", "Electrical minor", "Tile repair", "Door/window adjustment", "Other"],
    requiredInformation: "Categories of handyman work",
    tags: ["categories", "scope"],
  },
  {
    id: "handyman_estimated_hours",
    category: "project_size",
    priority: "high",
    question: "How long do you think the work will take?",
    questionType: "multiple_choice",
    choices: ["Under 2 hours", "Half day (2–4 hours)", "Full day (4–8 hours)", "Multiple days", "Not sure"],
    requiredInformation: "Estimated job duration",
    tags: ["duration", "hours"],
  },
  {
    id: "handyman_locations",
    category: "project_size",
    priority: "medium",
    question: "Where in the home is the work needed?",
    questionType: "checkbox",
    choices: ["Kitchen", "Bathroom", "Bedrooms", "Living areas", "Basement", "Garage", "Exterior", "Multiple areas"],
    requiredInformation: "Work locations in the home",
    tags: ["locations", "rooms"],
  },
  {
    id: "handyman_materials_needed",
    category: "project_size",
    priority: "medium",
    question: "Will materials be needed beyond basic supplies?",
    questionType: "multiple_choice",
    choices: ["No — labor only", "Minor supplies", "Specific materials needed", "Not sure"],
    requiredInformation: "Material requirements beyond labor",
    tags: ["materials", "supplies"],
  },
  {
    id: "handyman_issue_description",
    category: "existing_conditions",
    priority: "very_high",
    question: "Briefly describe what needs to be done",
    questionType: "short_text",
    requiredInformation: "Task description and details",
    tags: ["description", "issue"],
  },
  {
    id: "handyman_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current condition of the items or areas?",
    questionType: "multiple_choice",
    choices: ["Minor issue — quick fix", "Moderate repair needed", "Significant damage", "Not sure"],
    requiredInformation: "Current condition of work areas",
    tags: ["condition", "existing"],
  },
  {
    id: "handyman_previous_attempts",
    category: "existing_conditions",
    priority: "high",
    question: "Have you tried to fix this yourself?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — partial fix", "Yes — made it worse", "Someone else tried"],
    requiredInformation: "Previous repair attempts",
    tags: ["history", "diy"],
  },
  {
    id: "handyman_water_damage",
    category: "existing_conditions",
    priority: "high",
    question: "Is there any water damage involved?",
    questionType: "multiple_choice",
    choices: ["No", "Minor", "Significant", "Not sure"],
    requiredInformation: "Water damage involvement",
    tags: ["water_damage"],
  },
  {
    id: "handyman_structural_concern",
    category: "existing_conditions",
    priority: "medium",
    question: "Are there any structural concerns?",
    questionType: "multiple_choice",
    choices: ["No structural concerns", "Possible — not sure", "Yes — known structural issue"],
    requiredInformation: "Structural concern status",
    tags: ["structural", "safety"],
  },
  {
    id: "handyman_age_of_item",
    category: "existing_conditions",
    priority: "low",
    question: "How old is the item or fixture being repaired?",
    questionType: "multiple_choice",
    choices: ["Under 5 years", "5–15 years", "Over 15 years", "Not sure", "Not applicable"],
    requiredInformation: "Age of item being repaired",
    tags: ["age", "fixture"],
  },
  {
    id: "handyman_materials_supplied",
    category: "materials",
    priority: "high",
    question: "Will you supply materials or should the handyman?",
    questionType: "multiple_choice",
    choices: ["I'll supply materials", "Handyman supplies materials", "Mix", "Not sure"],
    requiredInformation: "Material supply responsibility",
    tags: ["materials", "supply"],
  },
  {
    id: "handyman_paint_color",
    category: "materials",
    priority: "medium",
    question: "If painting is involved, do you have the paint?",
    questionType: "multiple_choice",
    choices: ["Yes — paint on hand", "No — need paint purchased", "Not applicable"],
    requiredInformation: "Paint availability for touch-up work",
    tags: ["paint", "materials"],
  },
  {
    id: "handyman_hardware",
    category: "materials",
    priority: "medium",
    question: "If mounting or assembly, do you have the hardware?",
    questionType: "multiple_choice",
    choices: ["Yes — all hardware included", "Partial hardware", "Need hardware purchased", "Not applicable"],
    requiredInformation: "Hardware availability for mounting or assembly",
    tags: ["hardware", "mounting"],
  },
  {
    id: "handyman_fixture_type",
    category: "materials",
    priority: "low",
    question: "If installing a fixture, what type is it?",
    questionType: "multiple_choice",
    choices: ["Light fixture", "Ceiling fan", "Faucet or toilet", "Shelving or rod", "Appliance", "Not applicable", "Other"],
    requiredInformation: "Fixture type for installation",
    tags: ["fixture", "installation"],
  },
  {
    id: "handyman_tv_mounting",
    category: "special_features",
    priority: "medium",
    question: "Is TV or electronics mounting part of the work?",
    questionType: "multiple_choice",
    choices: ["No", "TV mounting", "Shelving for electronics", "Multiple mounts", "Not sure"],
    requiredInformation: "TV or electronics mounting scope",
    tags: ["tv", "mounting"],
  },
  {
    id: "handyman_furniture_assembly",
    category: "special_features",
    priority: "medium",
    question: "Is furniture assembly part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "1 item", "2–3 items", "4+ items", "Not sure"],
    requiredInformation: "Furniture assembly scope",
    tags: ["assembly", "furniture"],
  },
  {
    id: "handyman_weatherstripping",
    category: "special_features",
    priority: "low",
    question: "Is weatherstripping or draft sealing needed?",
    questionType: "multiple_choice",
    choices: ["No", "Doors only", "Windows only", "Doors and windows", "Not sure"],
    requiredInformation: "Weatherstripping scope",
    tags: ["weatherstripping", "sealing"],
  },
  {
    id: "handyman_childproofing",
    category: "special_features",
    priority: "low",
    question: "Is childproofing or safety work needed?",
    questionType: "yes_no",
    requiredInformation: "Childproofing or safety work needs",
    tags: ["childproofing", "safety"],
  },
  {
    id: "handyman_ladder_access",
    category: "access_removal",
    priority: "high",
    question: "Is ladder or elevated work required?",
    questionType: "multiple_choice",
    choices: ["No — ground level only", "Yes — ladder work", "Yes — high ceiling or exterior", "Not sure"],
    requiredInformation: "Ladder or elevated work requirements",
    tags: ["ladder", "height"],
  },
  {
    id: "handyman_clear_access",
    category: "access_removal",
    priority: "high",
    question: "Will the work area be clear and accessible?",
    questionType: "multiple_choice",
    choices: ["Yes — fully accessible", "Needs clearing first", "Tight or cramped space", "Not sure"],
    requiredInformation: "Work area accessibility",
    tags: ["access", "clearance"],
  },
  {
    id: "handyman_parking",
    category: "access_removal",
    priority: "medium",
    question: "Is parking available for the handyman?",
    questionType: "multiple_choice",
    choices: ["Yes — driveway or close", "Street parking", "Limited parking", "Not sure"],
    requiredInformation: "Parking availability",
    tags: ["parking", "access"],
  },
  {
    id: "handyman_pets",
    category: "access_removal",
    priority: "low",
    question: "Are there pets on site during the visit?",
    questionType: "multiple_choice",
    choices: ["No pets", "Pets — will be secured", "Pets — free roaming"],
    requiredInformation: "Pet presence on site",
    tags: ["pets", "safety"],
  },
  {
    id: "handyman_urgency",
    category: "timeline",
    priority: "very_high",
    question: "How soon do you need this done?",
    questionType: "multiple_choice",
    choices: ["Today or tomorrow", "This week", "Within 2 weeks", "Within 1 month", "Flexible"],
    requiredInformation: "Job urgency and scheduling",
    tags: ["urgency", "timeline"],
  },
  {
    id: "handyman_preferred_day",
    category: "timeline",
    priority: "high",
    question: "What days work best for you?",
    questionType: "multiple_choice",
    choices: ["Weekday mornings", "Weekday afternoons", "Weekends", "Any day", "Flexible"],
    requiredInformation: "Preferred scheduling days",
    tags: ["schedule", "availability"],
  },
  {
    id: "handyman_recurring",
    category: "timeline",
    priority: "low",
    question: "Is this a one-time job or recurring need?",
    questionType: "multiple_choice",
    choices: ["One-time", "Occasional as needed", "Regular maintenance schedule", "Not sure"],
    requiredInformation: "One-time vs recurring work",
    tags: ["recurring", "maintenance"],
  },
  {
    id: "handyman_licensed_trade",
    category: "customer_preferences",
    priority: "medium",
    question: "Does any work require a licensed trade (plumbing, electrical)?",
    questionType: "multiple_choice",
    choices: ["No — general handyman work", "Possibly — not sure", "Yes — licensed trade needed"],
    requiredInformation: "Licensed trade requirement",
    tags: ["licensed", "trade"],
  },
  {
    id: "handyman_insured",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you require the handyman to be insured?",
    questionType: "yes_no",
    requiredInformation: "Insurance requirement",
    tags: ["insured", "preferences"],
  },
  {
    id: "handyman_photo_available",
    category: "customer_preferences",
    priority: "medium",
    question: "Can you provide photos of the work area?",
    questionType: "yes_no",
    requiredInformation: "Photo availability for assessment",
    tags: ["photos", "assessment"],
  },
  {
    id: "handyman_previous_handyman",
    category: "customer_preferences",
    priority: "low",
    question: "Have you used a handyman for similar work before?",
    questionType: "multiple_choice",
    choices: ["No — first time", "Yes — positive experience", "Yes — negative experience"],
    requiredInformation: "Previous handyman experience",
    tags: ["history", "experience"],
  },
  {
    id: "handyman_tools_on_site",
    category: "customer_preferences",
    priority: "low",
    question: "Do you have any tools on site the handyman can use?",
    questionType: "multiple_choice",
    choices: ["No — handyman brings all tools", "Basic tools available", "Specific tools available"],
    requiredInformation: "On-site tool availability",
    tags: ["tools", "equipment"],
  },
  {
    id: "handyman_hoa_rules",
    category: "customer_preferences",
    priority: "low",
    question: "Are there HOA rules affecting the work?",
    questionType: "multiple_choice",
    choices: ["No HOA", "Yes — aware of rules", "Yes — not sure of rules"],
    requiredInformation: "HOA rules affecting work",
    tags: ["hoa", "rules"],
  },
  {
    id: "handyman_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is a workmanship guarantee important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship guarantee priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "handyman_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other quotes for this work?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
]);
