import { defineTradeQuestions } from "../builder";

export const HVAC_QUESTIONS = defineTradeQuestions("hvac", [
  {
    id: "hvac_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of HVAC work do you need?",
    questionType: "multiple_choice",
    choices: ["Repair", "Replacement", "New installation", "Maintenance / tune-up", "Ductwork", "Multiple items"],
    requiredInformation: "Primary HVAC project type",
    tags: ["scope", "type"],
  },
  {
    id: "hvac_system_count",
    category: "project_size",
    priority: "very_high",
    question: "How many HVAC systems are involved?",
    questionType: "multiple_choice",
    choices: ["1", "2", "3+", "Not sure"],
    requiredInformation: "Number of HVAC systems in scope",
    tags: ["systems", "scope"],
  },
  {
    id: "hvac_home_size",
    category: "project_size",
    priority: "high",
    question: "Approximate home square footage?",
    questionType: "multiple_choice",
    choices: ["Under 1,000 sq ft", "1,000–2,000 sq ft", "2,000–3,500 sq ft", "3,500–5,000 sq ft", "Over 5,000 sq ft", "Not sure"],
    requiredInformation: "Home size for system sizing",
    tags: ["size", "sqft"],
  },
  {
    id: "hvac_stories",
    category: "project_size",
    priority: "high",
    question: "How many stories does the home have?",
    questionType: "multiple_choice",
    choices: ["1 story", "2 stories", "3+ stories", "Split-level"],
    requiredInformation: "Number of stories for zoning and ductwork",
    tags: ["stories", "layout"],
  },
  {
    id: "hvac_zones",
    category: "project_size",
    priority: "medium",
    question: "How many heating/cooling zones do you need?",
    questionType: "multiple_choice",
    choices: ["Single zone", "2 zones", "3+ zones", "Not sure"],
    requiredInformation: "Number of HVAC zones desired",
    tags: ["zones", "scope"],
  },
  {
    id: "hvac_ductwork_scope",
    category: "project_size",
    priority: "medium",
    question: "Is ductwork part of this project?",
    questionType: "multiple_choice",
    choices: ["No ductwork work", "Repair existing ducts", "Replace some ducts", "Full duct replacement", "New duct installation", "Not sure"],
    requiredInformation: "Ductwork scope",
    tags: ["ductwork", "scope"],
  },
  {
    id: "hvac_current_system",
    category: "existing_conditions",
    priority: "very_high",
    question: "What type of system do you currently have?",
    questionType: "multiple_choice",
    choices: ["Central AC and furnace", "Heat pump", "Mini-split / ductless", "Boiler", "Window units", "No system", "Not sure"],
    requiredInformation: "Current HVAC system type",
    tags: ["existing", "system_type"],
  },
  {
    id: "hvac_system_age",
    category: "existing_conditions",
    priority: "very_high",
    question: "How old is your current HVAC system?",
    questionType: "multiple_choice",
    choices: ["Under 5 years", "5–10 years", "10–15 years", "15–20 years", "Over 20 years", "Not sure", "No existing system"],
    requiredInformation: "Current system age",
    tags: ["age", "existing"],
  },
  {
    id: "hvac_current_issue",
    category: "existing_conditions",
    priority: "very_high",
    question: "What problem are you experiencing?",
    questionType: "checkbox",
    choices: ["Not cooling", "Not heating", "Uneven temperatures", "High energy bills", "Strange noises", "Poor air quality", "System won't start", "Other"],
    requiredInformation: "Current HVAC issues or symptoms",
    tags: ["issues", "symptoms"],
  },
  {
    id: "hvac_no_heat_cool",
    category: "existing_conditions",
    priority: "high",
    question: "Is the system completely non-functional?",
    questionType: "multiple_choice",
    choices: ["Yes — no heat or cooling", "Partially working", "Working but inefficient", "Not applicable — new install"],
    requiredInformation: "System functionality status",
    tags: ["functionality", "urgent"],
  },
  {
    id: "hvac_fuel_type",
    category: "existing_conditions",
    priority: "high",
    question: "What fuel or energy source does your system use?",
    questionType: "multiple_choice",
    choices: ["Natural gas", "Propane", "Electric", "Oil", "Mixed", "Not sure"],
    requiredInformation: "Current fuel or energy source",
    tags: ["fuel", "energy"],
  },
  {
    id: "hvac_duct_condition",
    category: "existing_conditions",
    priority: "medium",
    question: "What is the condition of your existing ductwork?",
    questionType: "multiple_choice",
    choices: ["Good condition", "Some leaks or damage", "Poor — needs replacement", "No ductwork", "Not sure"],
    requiredInformation: "Existing ductwork condition",
    tags: ["ductwork", "condition"],
  },
  {
    id: "hvac_recent_service",
    category: "existing_conditions",
    priority: "medium",
    question: "When was the system last serviced?",
    questionType: "multiple_choice",
    choices: ["Within 6 months", "6–12 months ago", "1–2 years ago", "Over 2 years ago", "Never", "Not sure"],
    requiredInformation: "Last HVAC service date",
    tags: ["maintenance", "history"],
  },
  {
    id: "hvac_system_preference",
    category: "materials",
    priority: "high",
    question: "What type of system are you considering?",
    questionType: "multiple_choice",
    choices: ["Standard central AC/furnace", "Heat pump", "Mini-split / ductless", "High-efficiency upgrade", "Match existing type", "Contractor to advise"],
    requiredInformation: "Preferred replacement system type",
    tags: ["system_type", "preference"],
  },
  {
    id: "hvac_efficiency_priority",
    category: "materials",
    priority: "medium",
    question: "How important is energy efficiency?",
    questionType: "multiple_choice",
    choices: ["Top priority — highest efficiency", "Important — good efficiency", "Standard efficiency is fine", "Contractor to advise"],
    requiredInformation: "Energy efficiency priority",
    tags: ["efficiency", "energy"],
  },
  {
    id: "hvac_brand_preference",
    category: "materials",
    priority: "medium",
    question: "Do you have a preferred equipment brand?",
    questionType: "multiple_choice",
    choices: ["Yes — specific brand", "Premium brand", "Standard brand", "Best value", "No preference"],
    requiredInformation: "Equipment brand preference",
    tags: ["brand", "equipment"],
  },
  {
    id: "hvac_thermostat",
    category: "materials",
    priority: "medium",
    question: "Do you want a new thermostat included?",
    questionType: "multiple_choice",
    choices: ["Yes — smart thermostat", "Yes — programmable", "Yes — basic", "Keep existing thermostat", "Not sure"],
    requiredInformation: "Thermostat replacement preference",
    tags: ["thermostat", "controls"],
  },
  {
    id: "hvac_air_quality",
    category: "special_features",
    priority: "medium",
    question: "Are you interested in air quality add-ons?",
    questionType: "checkbox",
    choices: ["Air purifier", "Humidifier", "Dehumidifier", "UV light", "HEPA filtration", "None"],
    requiredInformation: "Air quality enhancement interests",
    tags: ["air_quality", "add_ons"],
  },
  {
    id: "hvac_mini_split_rooms",
    category: "special_features",
    priority: "medium",
    question: "If mini-split, how many rooms need units?",
    questionType: "multiple_choice",
    choices: ["1 room", "2–3 rooms", "4–6 rooms", "Whole home", "Not applicable"],
    requiredInformation: "Mini-split room count",
    tags: ["mini_split", "rooms"],
  },
  {
    id: "hvac_radiant_floor",
    category: "special_features",
    priority: "low",
    question: "Is radiant floor heating part of this project?",
    questionType: "yes_no",
    requiredInformation: "Radiant floor heating involvement",
    tags: ["radiant", "heating"],
  },
  {
    id: "hvac_permit",
    category: "special_features",
    priority: "medium",
    question: "Should the contractor handle permits and inspections?",
    questionType: "multiple_choice",
    choices: ["Yes — full permit handling", "I'll handle permits", "Not sure if permits needed"],
    requiredInformation: "Permit handling responsibility",
    tags: ["permits", "inspections"],
  },
  {
    id: "hvac_equipment_location",
    category: "access_removal",
    priority: "high",
    question: "Where is the current equipment located?",
    questionType: "multiple_choice",
    choices: ["Attic", "Basement / crawlspace", "Closet", "Garage", "Roof / rooftop", "Exterior pad", "Not sure"],
    requiredInformation: "Current equipment location",
    tags: ["location", "equipment"],
  },
  {
    id: "hvac_attic_access",
    category: "access_removal",
    priority: "medium",
    question: "Is attic or crawlspace access adequate for installation?",
    questionType: "multiple_choice",
    choices: ["Yes — easy access", "Limited access", "Difficult access", "Not applicable"],
    requiredInformation: "Attic or crawlspace access for installation",
    tags: ["access", "attic"],
  },
  {
    id: "hvac_old_equipment_removal",
    category: "access_removal",
    priority: "medium",
    question: "Should old equipment be removed and disposed of?",
    questionType: "yes_no",
    requiredInformation: "Old equipment removal and disposal",
    tags: ["removal", "disposal"],
  },
  {
    id: "hvac_electrical_panel",
    category: "access_removal",
    priority: "medium",
    question: "Is your electrical panel adequate for a new system?",
    questionType: "multiple_choice",
    choices: ["Yes", "No — may need upgrade", "Not sure"],
    requiredInformation: "Electrical panel capacity for HVAC",
    tags: ["electrical", "panel"],
  },
  {
    id: "hvac_urgency",
    category: "timeline",
    priority: "very_high",
    question: "How urgent is this HVAC need?",
    questionType: "multiple_choice",
    choices: ["Emergency — no heat or AC now", "Urgent — within a few days", "Soon — within 2 weeks", "Planning ahead — flexible"],
    requiredInformation: "HVAC urgency level",
    tags: ["urgency", "timeline"],
  },
  {
    id: "hvac_preferred_install_date",
    category: "timeline",
    priority: "high",
    question: "When would you like installation to occur?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 2 weeks", "Within 1 month", "Off-season (spring/fall)", "Flexible"],
    requiredInformation: "Preferred installation timeframe",
    tags: ["install", "timeline"],
  },
  {
    id: "hvac_seasonal_constraint",
    category: "timeline",
    priority: "medium",
    question: "Are you working around a specific season or event?",
    questionType: "multiple_choice",
    choices: ["No constraints", "Before summer", "Before winter", "Before selling home", "Other deadline"],
    requiredInformation: "Seasonal or event-driven timeline constraints",
    tags: ["season", "deadline"],
  },
  {
    id: "hvac_maintenance_plan",
    category: "customer_preferences",
    priority: "medium",
    question: "Are you interested in a maintenance plan?",
    questionType: "yes_no",
    requiredInformation: "Interest in HVAC maintenance plans",
    tags: ["maintenance", "ongoing"],
  },
  {
    id: "hvac_warranty_priority",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is equipment and labor warranty?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "hvac_noise_concern",
    category: "customer_preferences",
    priority: "low",
    question: "Is outdoor unit noise a concern?",
    questionType: "multiple_choice",
    choices: ["Yes — quiet operation important", "Somewhat", "Not a concern"],
    requiredInformation: "Outdoor unit noise sensitivity",
    tags: ["noise", "preferences"],
  },
  {
    id: "hvac_rebates",
    category: "customer_preferences",
    priority: "low",
    question: "Are you interested in utility rebates or tax credits?",
    questionType: "yes_no",
    requiredInformation: "Interest in rebates and incentives",
    tags: ["rebates", "incentives"],
  },
  {
    id: "hvac_filter_upgrade",
    category: "customer_preferences",
    priority: "low",
    question: "Are you interested in upgraded air filtration?",
    questionType: "multiple_choice",
    choices: ["Yes — HEPA or high-MERV filters", "Standard filters are fine", "Contractor to advise", "Not sure"],
    requiredInformation: "Air filtration upgrade interest",
    tags: ["filtration", "air_quality"],
  },
  {
    id: "hvac_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other HVAC quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "hvac_smart_home",
    category: "customer_preferences",
    priority: "low",
    question: "Do you want smart home integration for HVAC?",
    questionType: "yes_no",
    requiredInformation: "Smart home integration interest",
    tags: ["smart_home", "integration"],
  },
]);
