import { defineTradeQuestions } from "../builder";

export const KITCHEN_RENOVATION_QUESTIONS = defineTradeQuestions("kitchen_renovation", [
  {
    id: "kitchen_renovation_scope",
    category: "project_size",
    priority: "very_high",
    question: "What is the scope of your kitchen renovation?",
    questionType: "multiple_choice",
    choices: ["Cosmetic refresh", "Partial remodel", "Full gut renovation", "Cabinet refacing only", "Not sure"],
    requiredInformation: "Kitchen renovation scope level",
    tags: ["scope", "type"],
  },
  {
    id: "kitchen_renovation_size",
    category: "project_size",
    priority: "very_high",
    question: "Approximate kitchen size?",
    questionType: "multiple_choice",
    choices: ["Small (under 100 sq ft)", "Medium (100–200 sq ft)", "Large (200–350 sq ft)", "Extra large (350+ sq ft)", "Not sure"],
    requiredInformation: "Kitchen square footage",
    tags: ["size", "sqft"],
  },
  {
    id: "kitchen_renovation_layout_change",
    category: "project_size",
    priority: "very_high",
    question: "Are you changing the kitchen layout?",
    questionType: "multiple_choice",
    choices: ["No — same layout", "Minor changes", "Major layout change", "Remove or add walls", "Not sure"],
    requiredInformation: "Layout change scope",
    tags: ["layout", "structural"],
  },
  {
    id: "kitchen_renovation_components",
    category: "project_size",
    priority: "high",
    question: "Which components are included?",
    questionType: "checkbox",
    choices: ["Cabinets", "Countertops", "Backsplash", "Flooring", "Appliances", "Plumbing", "Electrical", "Lighting", "Other"],
    requiredInformation: "Renovation components in scope",
    tags: ["components", "scope"],
  },
  {
    id: "kitchen_renovation_island",
    category: "project_size",
    priority: "medium",
    question: "Is a kitchen island part of the plan?",
    questionType: "multiple_choice",
    choices: ["No island", "Add new island", "Replace existing island", "Modify existing island", "Not sure"],
    requiredInformation: "Kitchen island scope",
    tags: ["island", "layout"],
  },
  {
    id: "kitchen_renovation_cabinet_count",
    category: "project_size",
    priority: "medium",
    question: "Approximately how many linear feet of cabinetry?",
    questionType: "multiple_choice",
    choices: ["Under 15 ft", "15–25 ft", "25–40 ft", "Over 40 ft", "Not sure"],
    requiredInformation: "Cabinet linear footage",
    tags: ["cabinets", "size"],
  },
  {
    id: "kitchen_renovation_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current condition of your kitchen?",
    questionType: "multiple_choice",
    choices: ["Good — cosmetic updates only", "Fair — some components need replacing", "Poor — full renovation needed", "Not sure"],
    requiredInformation: "Current kitchen condition",
    tags: ["condition", "existing"],
  },
  {
    id: "kitchen_renovation_cabinet_condition",
    category: "existing_conditions",
    priority: "high",
    question: "What is the condition of existing cabinets?",
    questionType: "multiple_choice",
    choices: ["Good — keep or reface", "Fair — doors need replacing", "Poor — full replacement needed", "No existing cabinets", "Not sure"],
    requiredInformation: "Existing cabinet condition",
    tags: ["cabinets", "condition"],
  },
  {
    id: "kitchen_renovation_plumbing_condition",
    category: "existing_conditions",
    priority: "high",
    question: "Will plumbing need to be relocated?",
    questionType: "multiple_choice",
    choices: ["No relocation", "Minor adjustments", "Major relocation", "Not sure"],
    requiredInformation: "Plumbing relocation needs",
    tags: ["plumbing", "relocation"],
  },
  {
    id: "kitchen_renovation_electrical_condition",
    category: "existing_conditions",
    priority: "high",
    question: "Does electrical need upgrading?",
    questionType: "multiple_choice",
    choices: ["No upgrades needed", "Add circuits or outlets", "Panel upgrade needed", "Full electrical rework", "Not sure"],
    requiredInformation: "Electrical upgrade requirements",
    tags: ["electrical", "upgrade"],
  },
  {
    id: "kitchen_renovation_wall_removal",
    category: "existing_conditions",
    priority: "medium",
    question: "Are any walls being removed?",
    questionType: "multiple_choice",
    choices: ["No wall removal", "Non-load-bearing wall", "Possibly load-bearing wall", "Not sure"],
    requiredInformation: "Wall removal and structural implications",
    tags: ["walls", "structural"],
  },
  {
    id: "kitchen_renovation_water_damage",
    category: "existing_conditions",
    priority: "medium",
    question: "Is there water damage or mold in the kitchen?",
    questionType: "multiple_choice",
    choices: ["No", "Minor", "Significant", "Not sure"],
    requiredInformation: "Water damage or mold presence",
    tags: ["water_damage", "mold"],
  },
  {
    id: "kitchen_renovation_cabinet_style",
    category: "materials",
    priority: "high",
    question: "What cabinet style do you prefer?",
    questionType: "multiple_choice",
    choices: ["Shaker", "Flat panel / slab", "Raised panel", "Glass-front accents", "Open shelving", "Contractor to advise", "Not sure"],
    requiredInformation: "Cabinet style preference",
    tags: ["cabinets", "style"],
  },
  {
    id: "kitchen_renovation_countertop_material",
    category: "materials",
    priority: "high",
    question: "What countertop material do you want?",
    questionType: "multiple_choice",
    choices: ["Quartz", "Granite", "Marble", "Butcher block", "Laminate", "Concrete", "Not decided"],
    requiredInformation: "Countertop material preference",
    tags: ["countertops", "material"],
  },
  {
    id: "kitchen_renovation_backsplash",
    category: "materials",
    priority: "medium",
    question: "What backsplash material are you considering?",
    questionType: "multiple_choice",
    choices: ["Subway tile", "Large format tile", "Natural stone", "Glass tile", "No backsplash", "Not decided"],
    requiredInformation: "Backsplash material preference",
    tags: ["backsplash", "tile"],
  },
  {
    id: "kitchen_renovation_flooring_material",
    category: "materials",
    priority: "medium",
    question: "What flooring do you want in the kitchen?",
    questionType: "multiple_choice",
    choices: ["Tile", "Hardwood", "LVP / vinyl", "Keep existing", "Not decided"],
    requiredInformation: "Kitchen flooring material preference",
    tags: ["flooring", "material"],
  },
  {
    id: "kitchen_renovation_appliances",
    category: "materials",
    priority: "medium",
    question: "Are new appliances part of this project?",
    questionType: "multiple_choice",
    choices: ["No — keeping existing", "Some appliances", "All new appliances", "I'll supply appliances", "Not sure"],
    requiredInformation: "Appliance scope and supply",
    tags: ["appliances"],
  },
  {
    id: "kitchen_renovation_sink_faucet",
    category: "special_features",
    priority: "medium",
    question: "Are you upgrading the sink and faucet?",
    questionType: "multiple_choice",
    choices: ["No", "Faucet only", "Sink and faucet", "Farmhouse sink", "Not sure"],
    requiredInformation: "Sink and faucet upgrade scope",
    tags: ["sink", "faucet", "plumbing"],
  },
  {
    id: "kitchen_renovation_range_hood",
    category: "special_features",
    priority: "medium",
    question: "Is a new range hood or ventilation needed?",
    questionType: "multiple_choice",
    choices: ["No", "Replace existing hood", "Add new hood", "Upgrade to ducted ventilation", "Not sure"],
    requiredInformation: "Range hood and ventilation scope",
    tags: ["ventilation", "hood"],
  },
  {
    id: "kitchen_renovation_lighting",
    category: "special_features",
    priority: "medium",
    question: "What lighting updates are planned?",
    questionType: "checkbox",
    choices: ["Recessed lights", "Pendant lights", "Under-cabinet lighting", "Over-island lighting", "No lighting changes"],
    requiredInformation: "Kitchen lighting upgrade scope",
    tags: ["lighting"],
  },
  {
    id: "kitchen_renovation_pantry",
    category: "special_features",
    priority: "low",
    question: "Do you want a pantry or additional storage?",
    questionType: "multiple_choice",
    choices: ["No", "Built-in pantry cabinet", "Walk-in pantry", "Butler's pantry", "Not sure"],
    requiredInformation: "Pantry and storage additions",
    tags: ["pantry", "storage"],
  },
  {
    id: "kitchen_renovation_permits",
    category: "special_features",
    priority: "medium",
    question: "Should the contractor handle permits?",
    questionType: "multiple_choice",
    choices: ["Yes", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling preference",
    tags: ["permits"],
  },
  {
    id: "kitchen_renovation_temporary_kitchen",
    category: "access_removal",
    priority: "high",
    question: "How will you manage cooking during the renovation?",
    questionType: "multiple_choice",
    choices: ["Have alternate kitchen", "Use temporary setup", "Eat out / delivery", "Not sure"],
    requiredInformation: "Temporary kitchen arrangement during work",
    tags: ["temporary", "living"],
  },
  {
    id: "kitchen_renovation_demo",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle demolition and disposal?",
    questionType: "yes_no",
    requiredInformation: "Demolition and disposal responsibility",
    tags: ["demo", "disposal"],
  },
  {
    id: "kitchen_renovation_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there easy access for material delivery?",
    questionType: "multiple_choice",
    choices: ["Yes", "Limited access", "Difficult access", "Not sure"],
    requiredInformation: "Material delivery access",
    tags: ["access", "delivery"],
  },
  {
    id: "kitchen_renovation_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like the renovation to start?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 1 month", "Within 2–3 months", "Within 6 months", "Flexible"],
    requiredInformation: "Desired project start date",
    tags: ["timeline", "start"],
  },
  {
    id: "kitchen_renovation_deadline",
    category: "timeline",
    priority: "medium",
    question: "Do you have a completion deadline?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — event or holiday", "Yes — move-in date", "Yes — selling home", "Other"],
    requiredInformation: "Completion deadline",
    tags: ["deadline", "timeline"],
  },
  {
    id: "kitchen_renovation_design_help",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you need design assistance?",
    questionType: "multiple_choice",
    choices: ["Yes — full design help", "Some guidance needed", "I have a complete design", "Working with a designer already"],
    requiredInformation: "Design assistance needs",
    tags: ["design", "preferences"],
  },
  {
    id: "kitchen_renovation_style",
    category: "customer_preferences",
    priority: "medium",
    question: "What kitchen style are you going for?",
    questionType: "multiple_choice",
    choices: ["Modern", "Traditional", "Farmhouse", "Transitional", "Contemporary", "Not decided"],
    requiredInformation: "Kitchen design style preference",
    tags: ["style", "aesthetics"],
  },
  {
    id: "kitchen_renovation_quality_tier",
    category: "customer_preferences",
    priority: "medium",
    question: "What quality level are you targeting?",
    questionType: "multiple_choice",
    choices: ["Builder grade", "Mid-range", "High-end", "Luxury", "Contractor to advise"],
    requiredInformation: "Quality tier preference",
    tags: ["quality", "tier"],
  },
  {
    id: "kitchen_renovation_occupied",
    category: "customer_preferences",
    priority: "low",
    question: "Will you be living in the home during renovation?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during renovation",
    tags: ["occupied", "living"],
  },
  {
    id: "kitchen_renovation_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other kitchen renovation quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "kitchen_renovation_gc_preference",
    category: "customer_preferences",
    priority: "low",
    question: "Do you want one contractor to manage all trades?",
    questionType: "multiple_choice",
    choices: ["Yes — single general contractor", "I'll coordinate trades", "Not sure"],
    requiredInformation: "General contractor preference",
    tags: ["gc", "coordination"],
  },
  {
    id: "kitchen_renovation_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is a workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "kitchen_renovation_home_age",
    category: "existing_conditions",
    priority: "medium",
    question: "Approximately how old is the home?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–30 years", "30–50 years", "Over 50 years", "Not sure"],
    requiredInformation: "Home age affecting renovation complexity",
    tags: ["age", "home"],
  },
]);
