import { defineTradeQuestions } from "../builder";

export const LANDSCAPING_QUESTIONS = defineTradeQuestions("landscaping", [
  {
    id: "landscaping_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of landscaping work do you need?",
    questionType: "multiple_choice",
    choices: ["New landscape design", "Renovation / refresh", "Lawn care setup", "Hardscaping", "Irrigation", "Tree work", "Multiple items"],
    requiredInformation: "Primary landscaping project type",
    tags: ["scope", "type"],
  },
  {
    id: "landscaping_property_size",
    category: "project_size",
    priority: "very_high",
    question: "Approximate property or yard size?",
    questionType: "multiple_choice",
    choices: ["Small (under 5,000 sq ft)", "Medium (5,000–15,000 sq ft)", "Large (15,000–30,000 sq ft)", "Over 30,000 sq ft", "Not sure"],
    requiredInformation: "Property or yard size",
    tags: ["size", "property"],
  },
  {
    id: "landscaping_areas",
    category: "project_size",
    priority: "high",
    question: "Which areas are included?",
    questionType: "checkbox",
    choices: ["Front yard", "Backyard", "Side yards", "Driveway borders", "Pool area", "Entire property", "Other"],
    requiredInformation: "Landscaping areas in scope",
    tags: ["areas", "locations"],
  },
  {
    id: "landscaping_bed_linear_feet",
    category: "project_size",
    priority: "high",
    question: "Approximately how many linear feet of planting beds?",
    questionType: "multiple_choice",
    choices: ["Under 50 ft", "50–100 ft", "100–200 ft", "200–400 ft", "Over 400 ft", "Not sure"],
    requiredInformation: "Planting bed linear footage",
    tags: ["beds", "planting"],
  },
  {
    id: "landscaping_lawn_area",
    category: "project_size",
    priority: "medium",
    question: "Is lawn installation or repair part of this project?",
    questionType: "multiple_choice",
    choices: ["No lawn work", "Repair patches", "Reseed or sod sections", "Full lawn installation", "Not sure"],
    requiredInformation: "Lawn work scope",
    tags: ["lawn", "grass"],
  },
  {
    id: "landscaping_hardscape_scope",
    category: "project_size",
    priority: "medium",
    question: "Is hardscaping (patios, walkways, walls) included?",
    questionType: "multiple_choice",
    choices: ["No hardscaping", "Walkways or paths", "Patio or sitting area", "Retaining walls", "Multiple hardscape features", "Not sure"],
    requiredInformation: "Hardscaping scope",
    tags: ["hardscape", "patio"],
  },
  {
    id: "landscaping_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current state of your yard?",
    questionType: "multiple_choice",
    choices: ["Blank slate / new build", "Overgrown — needs clearing", "Dated — needs refresh", "Good — minor updates", "Not sure"],
    requiredInformation: "Current yard condition",
    tags: ["condition", "existing"],
  },
  {
    id: "landscaping_existing_plants",
    category: "existing_conditions",
    priority: "high",
    question: "Are there existing plants or trees to keep or remove?",
    questionType: "multiple_choice",
    choices: ["Keep most existing plants", "Remove some plants", "Remove all — start fresh", "No existing plants", "Not sure"],
    requiredInformation: "Existing plant retention or removal",
    tags: ["plants", "trees", "removal"],
  },
  {
    id: "landscaping_drainage_issues",
    category: "existing_conditions",
    priority: "high",
    question: "Do you have drainage or standing water issues?",
    questionType: "multiple_choice",
    choices: ["No drainage issues", "Minor pooling", "Significant drainage problems", "Not sure"],
    requiredInformation: "Drainage and standing water issues",
    tags: ["drainage", "water"],
  },
  {
    id: "landscaping_soil_condition",
    category: "existing_conditions",
    priority: "medium",
    question: "What is the soil condition?",
    questionType: "multiple_choice",
    choices: ["Good soil", "Clay-heavy", "Sandy", "Rocky", "Unknown — needs testing", "Not sure"],
    requiredInformation: "Soil type and condition",
    tags: ["soil", "condition"],
  },
  {
    id: "landscaping_slope",
    category: "existing_conditions",
    priority: "medium",
    question: "Is the yard sloped or on a hill?",
    questionType: "multiple_choice",
    choices: ["Mostly flat", "Gentle slope", "Moderate slope", "Steep slope", "Not sure"],
    requiredInformation: "Yard slope affecting design and drainage",
    tags: ["slope", "grade"],
  },
  {
    id: "landscaping_irrigation_existing",
    category: "existing_conditions",
    priority: "medium",
    question: "Is there an existing irrigation system?",
    questionType: "multiple_choice",
    choices: ["No irrigation", "Yes — working", "Yes — needs repair", "Yes — needs replacement", "Not sure"],
    requiredInformation: "Existing irrigation system status",
    tags: ["irrigation", "existing"],
  },
  {
    id: "landscaping_plant_preference",
    category: "materials",
    priority: "high",
    question: "What type of plants are you interested in?",
    questionType: "checkbox",
    choices: ["Trees", "Shrubs", "Perennials", "Annuals", "Native plants", "Drought-tolerant", "Edible garden", "Not sure"],
    requiredInformation: "Plant type preferences",
    tags: ["plants", "preference"],
  },
  {
    id: "landscaping_mulch_type",
    category: "materials",
    priority: "medium",
    question: "What ground cover do you prefer for beds?",
    questionType: "multiple_choice",
    choices: ["Wood mulch", "Rock / gravel", "Rubber mulch", "Ground cover plants", "Contractor to advise", "Not sure"],
    requiredInformation: "Mulch or ground cover preference",
    tags: ["mulch", "ground_cover"],
  },
  {
    id: "landscaping_hardscape_material",
    category: "materials",
    priority: "medium",
    question: "What hardscape material do you prefer?",
    questionType: "multiple_choice",
    choices: ["Pavers", "Natural stone", "Concrete", "Gravel", "Brick", "Not applicable", "Not sure"],
    requiredInformation: "Hardscape material preference",
    tags: ["hardscape", "material"],
  },
  {
    id: "landscaping_lawn_type",
    category: "materials",
    priority: "medium",
    question: "If installing lawn, what type do you prefer?",
    questionType: "multiple_choice",
    choices: ["Sod", "Seed", "Artificial turf", "Contractor to advise", "Not applicable"],
    requiredInformation: "Lawn installation type preference",
    tags: ["lawn", "sod", "seed"],
  },
  {
    id: "landscaping_lighting",
    category: "special_features",
    priority: "medium",
    question: "Is landscape lighting part of this project?",
    questionType: "multiple_choice",
    choices: ["No lighting", "Path lighting", "Accent / uplighting", "Full landscape lighting plan", "Not sure"],
    requiredInformation: "Landscape lighting scope",
    tags: ["lighting", "features"],
  },
  {
    id: "landscaping_water_feature",
    category: "special_features",
    priority: "low",
    question: "Are you interested in a water feature?",
    questionType: "multiple_choice",
    choices: ["No", "Fountain", "Pond", "Waterfall", "Not sure"],
    requiredInformation: "Water feature interest",
    tags: ["water_feature", "fountain"],
  },
  {
    id: "landscaping_fencing",
    category: "special_features",
    priority: "low",
    question: "Is fencing or privacy screening included?",
    questionType: "multiple_choice",
    choices: ["No", "Plant-based screening", "Decorative fence", "Full perimeter fence", "Not sure"],
    requiredInformation: "Fencing or screening scope",
    tags: ["fencing", "privacy"],
  },
  {
    id: "landscaping_outdoor_living",
    category: "special_features",
    priority: "medium",
    question: "Are outdoor living features included?",
    questionType: "checkbox",
    choices: ["Fire pit", "Outdoor kitchen", "Pergola", "Seating area", "Play area", "None"],
    requiredInformation: "Outdoor living feature scope",
    tags: ["outdoor_living", "features"],
  },
  {
    id: "landscaping_irrigation_new",
    category: "special_features",
    priority: "medium",
    question: "Do you need a new or upgraded irrigation system?",
    questionType: "multiple_choice",
    choices: ["No", "Repair existing", "Add zones to existing", "Full new system", "Not sure"],
    requiredInformation: "Irrigation system scope",
    tags: ["irrigation", "system"],
  },
  {
    id: "landscaping_site_access",
    category: "access_removal",
    priority: "high",
    question: "Is there equipment access to all work areas?",
    questionType: "multiple_choice",
    choices: ["Yes — full access", "Limited — narrow gates", "Difficult — obstacles", "Not sure"],
    requiredInformation: "Equipment and material access",
    tags: ["access", "equipment"],
  },
  {
    id: "landscaping_debris_removal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle debris and plant removal?",
    questionType: "yes_no",
    requiredInformation: "Debris and plant removal responsibility",
    tags: ["removal", "disposal"],
  },
  {
    id: "landscaping_underground_utilities",
    category: "access_removal",
    priority: "medium",
    question: "Are there underground utilities or irrigation lines to avoid?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Possible — need locates", "Known lines in work area", "Not sure"],
    requiredInformation: "Underground utility concerns",
    tags: ["utilities", "underground"],
  },
  {
    id: "landscaping_hoa_rules",
    category: "access_removal",
    priority: "medium",
    question: "Are there HOA landscaping rules to follow?",
    questionType: "multiple_choice",
    choices: ["No HOA", "Yes — I know the rules", "Yes — need guidance", "Not sure"],
    requiredInformation: "HOA landscaping restrictions",
    tags: ["hoa", "rules"],
  },
  {
    id: "landscaping_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like work to begin?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "This season", "Next season", "Within 3 months", "Flexible"],
    requiredInformation: "Desired project start date",
    tags: ["timeline", "start"],
  },
  {
    id: "landscaping_seasonal_constraint",
    category: "timeline",
    priority: "medium",
    question: "Are there seasonal constraints?",
    questionType: "multiple_choice",
    choices: ["No constraints", "Must plant by a certain date", "Avoid winter work", "Event deadline", "Flexible"],
    requiredInformation: "Seasonal timing constraints",
    tags: ["season", "timeline"],
  },
  {
    id: "landscaping_maintenance_plan",
    category: "timeline",
    priority: "low",
    question: "Are you interested in ongoing maintenance?",
    questionType: "multiple_choice",
    choices: ["No — one-time project", "Yes — regular maintenance", "Maybe — want to discuss", "Not sure"],
    requiredInformation: "Ongoing maintenance interest",
    tags: ["maintenance", "ongoing"],
  },
  {
    id: "landscaping_design_help",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you need landscape design assistance?",
    questionType: "multiple_choice",
    choices: ["Yes — full design", "Some guidance", "I have a plan already", "Working with a designer"],
    requiredInformation: "Design assistance needs",
    tags: ["design", "preferences"],
  },
  {
    id: "landscaping_style",
    category: "customer_preferences",
    priority: "medium",
    question: "What landscape style do you prefer?",
    questionType: "multiple_choice",
    choices: ["Formal / structured", "Natural / cottage", "Modern / minimalist", "Tropical", "Xeriscape / low water", "Not decided"],
    requiredInformation: "Landscape style preference",
    tags: ["style", "aesthetics"],
  },
  {
    id: "landscaping_low_maintenance",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is low maintenance?",
    questionType: "multiple_choice",
    choices: ["Top priority", "Important", "Moderate", "Not a concern"],
    requiredInformation: "Low-maintenance priority",
    tags: ["maintenance", "preferences"],
  },
  {
    id: "landscaping_pets_kids",
    category: "customer_preferences",
    priority: "low",
    question: "Do pets or children affect your landscaping needs?",
    questionType: "multiple_choice",
    choices: ["No", "Pets", "Children", "Both pets and children"],
    requiredInformation: "Pet and child considerations",
    tags: ["pets", "kids", "safety"],
  },
  {
    id: "landscaping_sun_exposure",
    category: "existing_conditions",
    priority: "medium",
    question: "What is the sun exposure in the main work areas?",
    questionType: "multiple_choice",
    choices: ["Full sun", "Partial sun / shade", "Mostly shade", "Mixed across property", "Not sure"],
    requiredInformation: "Sun exposure for plant selection",
    tags: ["sun", "exposure"],
  },
  {
    id: "landscaping_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other landscaping quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "landscaping_warranty",
    category: "customer_preferences",
    priority: "low",
    question: "Is a plant or workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Warranty priority",
    tags: ["warranty", "preferences"],
  },
]);
