import { defineTradeQuestions } from "../builder";

export const OTHER_QUESTIONS = defineTradeQuestions("other", [
  {
    id: "other_project_description",
    category: "project_size",
    priority: "very_high",
    question: "Briefly describe the project you need help with",
    questionType: "short_text",
    requiredInformation: "Project description and scope",
    tags: ["description", "scope"],
  },
  {
    id: "other_trade_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of contractor or trade do you think you need?",
    questionType: "multiple_choice",
    choices: ["Not sure — need guidance", "General contractor", "Specialty trade", "Multiple trades", "Consultation only"],
    requiredInformation: "Contractor or trade type needed",
    tags: ["trade", "type"],
  },
  {
    id: "other_project_scope",
    category: "project_size",
    priority: "very_high",
    question: "How would you describe the project size?",
    questionType: "multiple_choice",
    choices: ["Small — single task", "Medium — one room or area", "Large — multiple rooms", "Major — whole home or property", "Not sure"],
    requiredInformation: "Overall project size",
    tags: ["size", "scope"],
  },
  {
    id: "other_square_footage",
    category: "project_size",
    priority: "high",
    question: "Approximate area affected (if applicable)?",
    questionType: "multiple_choice",
    choices: ["Under 100 sq ft", "100–500 sq ft", "500–2,000 sq ft", "Over 2,000 sq ft", "Not applicable", "Not sure"],
    requiredInformation: "Approximate affected area",
    tags: ["size", "sqft"],
  },
  {
    id: "other_property_type",
    category: "project_size",
    priority: "high",
    question: "What type of property is this?",
    questionType: "multiple_choice",
    choices: ["Single-family home", "Townhouse / condo", "Apartment", "Commercial", "Rental property", "Other"],
    requiredInformation: "Property type",
    tags: ["property", "type"],
  },
  {
    id: "other_locations",
    category: "project_size",
    priority: "medium",
    question: "Where on the property is the work needed?",
    questionType: "checkbox",
    choices: ["Interior", "Exterior", "Basement", "Attic", "Garage", "Yard", "Roof", "Other"],
    requiredInformation: "Work locations on property",
    tags: ["locations", "areas"],
  },
  {
    id: "other_item_count",
    category: "project_size",
    priority: "medium",
    question: "How many items or areas are involved?",
    questionType: "multiple_choice",
    choices: ["1", "2–3", "4–6", "7+", "Not sure"],
    requiredInformation: "Number of items or areas in scope",
    tags: ["count", "scope"],
  },
  {
    id: "other_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current condition?",
    questionType: "multiple_choice",
    choices: ["Good — minor work", "Fair — moderate work needed", "Poor — major work needed", "New build / blank slate", "Not sure"],
    requiredInformation: "Current condition of work area",
    tags: ["condition", "existing"],
  },
  {
    id: "other_known_issues",
    category: "existing_conditions",
    priority: "very_high",
    question: "Are there known issues to address?",
    questionType: "checkbox",
    choices: ["Water damage", "Structural concern", "Mold or mildew", "Pest damage", "Code violations", "Safety hazard", "None known", "Other"],
    requiredInformation: "Known issues requiring attention",
    tags: ["issues", "problems"],
  },
  {
    id: "other_home_age",
    category: "existing_conditions",
    priority: "high",
    question: "Approximately how old is the property?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–30 years", "30–50 years", "Over 50 years", "New construction", "Not sure"],
    requiredInformation: "Property age",
    tags: ["age", "property"],
  },
  {
    id: "other_previous_work",
    category: "existing_conditions",
    priority: "high",
    question: "Has similar work been done before on this property?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — recently", "Yes — long ago", "Not sure"],
    requiredInformation: "Previous similar work history",
    tags: ["history", "previous_work"],
  },
  {
    id: "other_urgency_level",
    category: "existing_conditions",
    priority: "high",
    question: "Is there an urgent or safety issue?",
    questionType: "multiple_choice",
    choices: ["Yes — safety emergency", "Yes — urgent but not emergency", "No — can wait", "Not sure"],
    requiredInformation: "Urgency and safety status",
    tags: ["urgency", "safety"],
  },
  {
    id: "other_access_limitations",
    category: "existing_conditions",
    priority: "medium",
    question: "Are there access limitations to the work area?",
    questionType: "multiple_choice",
    choices: ["No limitations", "Tight or confined space", "Height or ladder required", "Special equipment needed", "Not sure"],
    requiredInformation: "Access limitations",
    tags: ["access", "limitations"],
  },
  {
    id: "other_materials_preference",
    category: "materials",
    priority: "high",
    question: "Do you have material preferences?",
    questionType: "multiple_choice",
    choices: ["Yes — specific materials in mind", "Standard quality", "Premium quality", "Contractor to recommend", "No preference", "Not sure"],
    requiredInformation: "Material quality and preference",
    tags: ["materials", "preference"],
  },
  {
    id: "other_materials_supplied",
    category: "materials",
    priority: "medium",
    question: "Will you supply materials or should the contractor?",
    questionType: "multiple_choice",
    choices: ["I'll supply materials", "Contractor supplies all", "Mix", "Not sure yet"],
    requiredInformation: "Material supply responsibility",
    tags: ["materials", "supply"],
  },
  {
    id: "other_brand_preference",
    category: "materials",
    priority: "low",
    question: "Do you have a specific brand or product in mind?",
    questionType: "multiple_choice",
    choices: ["Yes — specific brand", "General preference", "No preference", "Not applicable"],
    requiredInformation: "Brand or product preference",
    tags: ["brand", "product"],
  },
  {
    id: "other_special_requirements",
    category: "special_features",
    priority: "medium",
    question: "Are there special requirements for this project?",
    questionType: "checkbox",
    choices: ["Permits required", "HOA approval", "Historic preservation", "Accessibility / ADA", "Eco-friendly materials", "None", "Other"],
    requiredInformation: "Special project requirements",
    tags: ["requirements", "special"],
  },
  {
    id: "other_custom_work",
    category: "special_features",
    priority: "medium",
    question: "Is custom or specialty work involved?",
    questionType: "multiple_choice",
    choices: ["No — standard work", "Some custom elements", "Fully custom project", "Not sure"],
    requiredInformation: "Custom work scope",
    tags: ["custom", "specialty"],
  },
  {
    id: "other_design_plans",
    category: "special_features",
    priority: "medium",
    question: "Do you have plans, drawings, or inspiration images?",
    questionType: "multiple_choice",
    choices: ["Yes — detailed plans", "Yes — inspiration images only", "Ideas but no plans", "No plans yet"],
    requiredInformation: "Design plan availability",
    tags: ["plans", "design"],
  },
  {
    id: "other_multiple_trades",
    category: "special_features",
    priority: "low",
    question: "Will multiple trades need to coordinate?",
    questionType: "multiple_choice",
    choices: ["No — single trade", "Yes — 2–3 trades", "Yes — many trades", "Not sure"],
    requiredInformation: "Multi-trade coordination needs",
    tags: ["trades", "coordination"],
  },
  {
    id: "other_demo_needed",
    category: "access_removal",
    priority: "high",
    question: "Is demolition or removal part of the project?",
    questionType: "multiple_choice",
    choices: ["No", "Minor removal", "Significant demolition", "Not sure"],
    requiredInformation: "Demolition or removal scope",
    tags: ["demo", "removal"],
  },
  {
    id: "other_disposal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle debris disposal?",
    questionType: "yes_no",
    requiredInformation: "Debris disposal responsibility",
    tags: ["disposal", "debris"],
  },
  {
    id: "other_site_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there adequate site access for workers and materials?",
    questionType: "multiple_choice",
    choices: ["Yes", "Limited access", "Difficult access", "Not sure"],
    requiredInformation: "Site access for work",
    tags: ["access", "site"],
  },
  {
    id: "other_occupied",
    category: "access_removal",
    priority: "medium",
    question: "Will the property be occupied during work?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during project",
    tags: ["occupied", "living"],
  },
  {
    id: "other_parking",
    category: "access_removal",
    priority: "low",
    question: "Is parking available for the contractor?",
    questionType: "multiple_choice",
    choices: ["Yes", "Street parking only", "Limited", "Not sure"],
    requiredInformation: "Contractor parking availability",
    tags: ["parking", "access"],
  },
  {
    id: "other_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like work to begin?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 2 weeks", "Within 1 month", "Within 2–3 months", "Flexible"],
    requiredInformation: "Desired start date",
    tags: ["timeline", "start"],
  },
  {
    id: "other_deadline",
    category: "timeline",
    priority: "high",
    question: "Do you have a completion deadline?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — specific date", "Yes — event or season", "Yes — selling or moving", "Other"],
    requiredInformation: "Completion deadline",
    tags: ["deadline", "timeline"],
  },
  {
    id: "other_flexibility",
    category: "timeline",
    priority: "medium",
    question: "How flexible is your timeline?",
    questionType: "multiple_choice",
    choices: ["Very flexible", "Somewhat flexible", "Fixed deadline", "Not sure"],
    requiredInformation: "Timeline flexibility",
    tags: ["flexibility", "timeline"],
  },
  {
    id: "other_contractor_preference",
    category: "customer_preferences",
    priority: "medium",
    question: "What matters most when choosing a contractor?",
    questionType: "checkbox",
    choices: ["Licensed and insured", "Reviews and reputation", "Fastest availability", "Quality of work", "Clear communication", "Warranty"],
    requiredInformation: "Contractor selection priorities",
    tags: ["preferences", "selection"],
  },
  {
    id: "other_design_help",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you need help defining the scope or design?",
    questionType: "multiple_choice",
    choices: ["Yes — need full guidance", "Some guidance", "No — I know what I want", "Working with a designer"],
    requiredInformation: "Scope and design guidance needs",
    tags: ["design", "guidance"],
  },
  {
    id: "other_warranty",
    category: "customer_preferences",
    priority: "medium",
    question: "Is a workmanship warranty important?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "other_licensed_insured",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you require a licensed and insured contractor?",
    questionType: "yes_no",
    requiredInformation: "Licensing and insurance requirement",
    tags: ["licensed", "insured"],
  },
  {
    id: "other_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "other_referral_source",
    category: "customer_preferences",
    priority: "low",
    question: "How did you hear about this service?",
    questionType: "multiple_choice",
    choices: ["Online search", "Referral from friend", "Social media", "Previous customer", "Other"],
    requiredInformation: "Referral or discovery source",
    tags: ["referral", "source"],
  },
  {
    id: "other_additional_notes",
    category: "customer_preferences",
    priority: "low",
    question: "Anything else the contractor should know upfront?",
    questionType: "short_text",
    requiredInformation: "Additional context for contractor",
    tags: ["notes", "context"],
  },
]);
