import { defineTradeQuestions } from "../builder";

export const PAINTER_QUESTIONS = defineTradeQuestions("painter", [
  {
    id: "painter_room_count",
    category: "project_size",
    priority: "very_high",
    question: "How many rooms need painting?",
    questionType: "multiple_choice",
    choices: ["1 room", "2–3 rooms", "4–6 rooms", "7+ rooms", "Whole home interior"],
    requiredInformation: "Number of rooms to be painted",
    tags: ["interior", "scope", "rooms"],
  },
  {
    id: "painter_interior_exterior",
    category: "project_size",
    priority: "very_high",
    question: "Is this interior, exterior, or both?",
    questionType: "multiple_choice",
    choices: ["Interior only", "Exterior only", "Both interior and exterior"],
    requiredInformation: "Interior vs exterior scope",
    tags: ["scope", "interior", "exterior"],
  },
  {
    id: "painter_square_footage",
    category: "project_size",
    priority: "high",
    question: "Approximate square footage to be painted?",
    questionType: "multiple_choice",
    choices: ["Under 500 sq ft", "500–1,000 sq ft", "1,000–2,500 sq ft", "2,500–5,000 sq ft", "Over 5,000 sq ft", "Not sure"],
    requiredInformation: "Approximate painted area",
    tags: ["scope", "size"],
  },
  {
    id: "painter_ceiling_height",
    category: "project_size",
    priority: "high",
    question: "What are the ceiling heights in the areas to be painted?",
    questionType: "multiple_choice",
    choices: ["Standard (8 ft)", "9 ft", "10+ ft or vaulted", "Mixed heights", "Not sure"],
    requiredInformation: "Ceiling height for labor and equipment planning",
    tags: ["ceilings", "access", "height"],
  },
  {
    id: "painter_stories",
    category: "project_size",
    priority: "high",
    question: "How many stories are involved (exterior or interior)?",
    questionType: "multiple_choice",
    choices: ["Single story", "Two stories", "Three or more", "Not applicable"],
    requiredInformation: "Number of stories affecting access and scope",
    tags: ["exterior", "access", "stories"],
  },
  {
    id: "painter_surface_types",
    category: "project_size",
    priority: "high",
    question: "Which surfaces need painting?",
    questionType: "checkbox",
    choices: ["Walls", "Ceilings", "Trim and baseboards", "Doors", "Cabinets", "Siding", "Deck or fence", "Other"],
    requiredInformation: "Surface types included in scope",
    tags: ["surfaces", "scope"],
  },
  {
    id: "painter_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the current condition of the surfaces?",
    questionType: "multiple_choice",
    choices: ["Good — light refresh", "Fair — some repairs needed", "Poor — significant prep required", "Not sure"],
    requiredInformation: "Surface condition and prep level needed",
    tags: ["prep", "condition"],
  },
  {
    id: "painter_existing_paint",
    category: "existing_conditions",
    priority: "very_high",
    question: "Is there existing paint on the surfaces?",
    questionType: "yes_no",
    requiredInformation: "Whether existing paint is present",
    tags: ["existing", "paint"],
  },
  {
    id: "painter_peeling_cracking",
    category: "existing_conditions",
    priority: "high",
    question: "Is there peeling, cracking, or flaking paint?",
    questionType: "multiple_choice",
    choices: ["None", "Minor areas", "Moderate areas", "Widespread", "Not sure"],
    requiredInformation: "Extent of paint failure requiring prep",
    tags: ["prep", "damage", "peeling"],
  },
  {
    id: "painter_water_damage",
    category: "existing_conditions",
    priority: "high",
    question: "Is there water damage, stains, or mold on any surfaces?",
    questionType: "multiple_choice",
    choices: ["No", "Minor stains only", "Water damage present", "Mold or mildew present", "Not sure"],
    requiredInformation: "Water damage or mold affecting prep and remediation",
    tags: ["water_damage", "mold", "stains"],
  },
  {
    id: "painter_lead_paint",
    category: "existing_conditions",
    priority: "high",
    question: "Was the home built before 1978 (potential lead paint)?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Not sure"],
    requiredInformation: "Lead paint risk for older homes",
    tags: ["lead", "safety", "prep"],
  },
  {
    id: "painter_wall_texture",
    category: "existing_conditions",
    priority: "medium",
    question: "What wall texture do you currently have?",
    questionType: "multiple_choice",
    choices: ["Smooth", "Light texture", "Heavy texture / orange peel", "Popcorn ceiling", "Mixed", "Not sure"],
    requiredInformation: "Wall and ceiling texture type",
    tags: ["texture", "walls", "ceilings"],
  },
  {
    id: "painter_previous_paint_type",
    category: "existing_conditions",
    priority: "medium",
    question: "Do you know what type of paint is currently on the surfaces?",
    questionType: "multiple_choice",
    choices: ["Latex / water-based", "Oil-based / alkyd", "Not sure", "New construction — no paint yet"],
    requiredInformation: "Existing paint chemistry for compatibility",
    tags: ["paint_type", "compatibility"],
  },
  {
    id: "painter_color_change",
    category: "materials",
    priority: "high",
    question: "Are you changing colors or refreshing the same color?",
    questionType: "multiple_choice",
    choices: ["Same color refresh", "Similar shade", "Significant color change (light to dark or vice versa)", "Not decided"],
    requiredInformation: "Color change affecting coats and primer needs",
    tags: ["color", "primer"],
  },
  {
    id: "painter_paint_quality",
    category: "materials",
    priority: "medium",
    question: "What paint quality do you prefer?",
    questionType: "multiple_choice",
    choices: ["Standard", "Premium", "Contractor to recommend", "Not sure"],
    requiredInformation: "Paint quality tier preference",
    tags: ["paint", "materials"],
  },
  {
    id: "painter_finish_preference",
    category: "materials",
    priority: "medium",
    question: "What sheen or finish do you prefer?",
    questionType: "multiple_choice",
    choices: ["Flat / matte", "Eggshell", "Satin", "Semi-gloss", "Gloss", "Mixed by room", "Contractor to advise"],
    requiredInformation: "Preferred paint finish by area",
    tags: ["finish", "sheen"],
  },
  {
    id: "painter_primer_needed",
    category: "materials",
    priority: "medium",
    question: "Do you want primer applied?",
    questionType: "multiple_choice",
    choices: ["Yes — all surfaces", "Yes — problem areas only", "No — paint only", "Contractor to advise"],
    requiredInformation: "Primer scope preference",
    tags: ["primer", "materials"],
  },
  {
    id: "painter_eco_friendly",
    category: "materials",
    priority: "low",
    question: "Do you prefer low-VOC or eco-friendly paint?",
    questionType: "yes_no",
    requiredInformation: "Low-VOC or eco-friendly paint preference",
    tags: ["eco", "low_voc"],
  },
  {
    id: "painter_cabinet_painting",
    category: "special_features",
    priority: "medium",
    question: "Do any cabinets need painting?",
    questionType: "multiple_choice",
    choices: ["No", "Kitchen cabinets", "Bathroom cabinets", "Both kitchen and bathroom", "Other cabinets"],
    requiredInformation: "Cabinet painting scope",
    tags: ["cabinets", "kitchen", "bathroom"],
  },
  {
    id: "painter_trim_detail",
    category: "special_features",
    priority: "medium",
    question: "Is detailed trim work involved (crown molding, wainscoting, etc.)?",
    questionType: "multiple_choice",
    choices: ["No trim work", "Standard trim only", "Detailed or decorative trim", "Not sure"],
    requiredInformation: "Trim detail level affecting labor",
    tags: ["trim", "detail"],
  },
  {
    id: "painter_wallpaper_removal",
    category: "special_features",
    priority: "medium",
    question: "Does wallpaper need to be removed?",
    questionType: "yes_no",
    requiredInformation: "Wallpaper removal requirement",
    tags: ["wallpaper", "removal", "prep"],
  },
  {
    id: "painter_pressure_washing",
    category: "special_features",
    priority: "medium",
    question: "Is pressure washing needed before exterior painting?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Not sure", "Not applicable — interior only"],
    requiredInformation: "Exterior pressure washing need",
    tags: ["exterior", "pressure_washing", "prep"],
  },
  {
    id: "painter_caulking_repairs",
    category: "special_features",
    priority: "medium",
    question: "Is caulking or minor wood repair needed?",
    questionType: "multiple_choice",
    choices: ["No repairs needed", "Caulking only", "Minor wood repair and caulking", "Significant repairs needed", "Not sure"],
    requiredInformation: "Caulking and minor repair scope",
    tags: ["caulking", "repairs", "prep"],
  },
  {
    id: "painter_furniture_move",
    category: "access_removal",
    priority: "high",
    question: "Who will move furniture and cover floors?",
    questionType: "multiple_choice",
    choices: ["Contractor handles everything", "I'll move furniture — contractor covers floors", "I'll handle all prep and covering", "Not sure"],
    requiredInformation: "Furniture moving and floor protection responsibility",
    tags: ["furniture", "prep", "access"],
  },
  {
    id: "painter_occupied_home",
    category: "access_removal",
    priority: "high",
    question: "Will the home be occupied during painting?",
    questionType: "yes_no",
    requiredInformation: "Occupied vs vacant property during work",
    tags: ["occupied", "access"],
  },
  {
    id: "painter_parking_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there convenient parking and access for the crew?",
    questionType: "multiple_choice",
    choices: ["Yes — driveway or close parking", "Street parking available", "Limited access", "Not sure"],
    requiredInformation: "Site access and parking for crew and equipment",
    tags: ["parking", "access"],
  },
  {
    id: "painter_debris_disposal",
    category: "access_removal",
    priority: "medium",
    question: "Should the contractor handle debris and paint can disposal?",
    questionType: "yes_no",
    requiredInformation: "Debris and disposal responsibility",
    tags: ["disposal", "cleanup"],
  },
  {
    id: "painter_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like work to begin?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 2 weeks", "Within 1 month", "Within 2–3 months", "Flexible"],
    requiredInformation: "Desired project start timeframe",
    tags: ["timeline", "start"],
  },
  {
    id: "painter_weather_constraint",
    category: "timeline",
    priority: "medium",
    question: "Are there weather constraints for exterior work?",
    questionType: "multiple_choice",
    choices: ["No constraints", "Prefer a specific season", "Must complete before a date", "Not applicable — interior only"],
    requiredInformation: "Weather or seasonal constraints for exterior painting",
    tags: ["weather", "exterior", "timeline"],
  },
  {
    id: "painter_specific_deadline",
    category: "timeline",
    priority: "medium",
    question: "Do you have a hard deadline for completion?",
    questionType: "multiple_choice",
    choices: ["No deadline", "Yes — event or move-in date", "Yes — selling the home", "Other deadline"],
    requiredInformation: "Hard completion deadline if any",
    tags: ["deadline", "timeline"],
  },
  {
    id: "painter_color_selection",
    category: "customer_preferences",
    priority: "medium",
    question: "Have you selected your paint colors?",
    questionType: "multiple_choice",
    choices: ["Yes — colors chosen", "Narrowed to a few options", "Need color consultation", "Contractor to advise"],
    requiredInformation: "Color selection status",
    tags: ["color", "selection"],
  },
  {
    id: "painter_color_consultation",
    category: "customer_preferences",
    priority: "low",
    question: "Would you like help with color selection?",
    questionType: "yes_no",
    requiredInformation: "Interest in color consultation services",
    tags: ["color", "consultation"],
  },
  {
    id: "painter_warranty_interest",
    category: "customer_preferences",
    priority: "low",
    question: "Is a workmanship warranty important to you?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Workmanship warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "painter_previous_contractor",
    category: "customer_preferences",
    priority: "low",
    question: "Have you had this area painted recently?",
    questionType: "multiple_choice",
    choices: ["No — first time or long ago", "Yes — within the last year", "Yes — 1–3 years ago", "Yes — unhappy with previous work"],
    requiredInformation: "Recent painting history",
    tags: ["history", "previous_work"],
  },
  {
    id: "painter_coat_count",
    category: "customer_preferences",
    priority: "low",
    question: "How many coats of paint do you expect?",
    questionType: "multiple_choice",
    choices: ["One coat", "Two coats", "Whatever is needed for coverage", "Contractor to advise"],
    requiredInformation: "Expected number of paint coats",
    tags: ["coats", "coverage"],
  },
]);
