import { defineTradeQuestions } from "../builder";

export const PLUMBER_QUESTIONS = defineTradeQuestions("plumber", [
  {
    id: "plumber_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of plumbing work do you need?",
    questionType: "multiple_choice",
    choices: ["Repair", "Replacement", "New installation", "Remodel", "Inspection or diagnosis", "Multiple items"],
    requiredInformation: "Primary plumbing project type",
    tags: ["scope", "type"],
  },
  {
    id: "plumber_fixture_count",
    category: "project_size",
    priority: "very_high",
    question: "How many fixtures or appliances are involved?",
    questionType: "multiple_choice",
    choices: ["1", "2–3", "4–6", "7+", "Whole-home repipe"],
    requiredInformation: "Number of fixtures or appliances in scope",
    tags: ["fixtures", "scope"],
  },
  {
    id: "plumber_locations",
    category: "project_size",
    priority: "high",
    question: "Which areas are affected?",
    questionType: "checkbox",
    choices: ["Kitchen", "Bathroom", "Laundry", "Basement", "Exterior", "Whole house", "Other"],
    requiredInformation: "Locations requiring plumbing work",
    tags: ["locations", "scope"],
  },
  {
    id: "plumber_pipe_scope",
    category: "project_size",
    priority: "high",
    question: "How much piping is involved?",
    questionType: "multiple_choice",
    choices: ["Single connection or short run", "One room", "Multiple rooms", "Whole-house repipe", "Not sure"],
    requiredInformation: "Extent of piping work",
    tags: ["pipes", "scope"],
  },
  {
    id: "plumber_water_heater",
    category: "project_size",
    priority: "high",
    question: "Is a water heater part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "Repair existing", "Replace existing", "New installation", "Not sure"],
    requiredInformation: "Water heater scope",
    tags: ["water_heater", "scope"],
  },
  {
    id: "plumber_fixture_types",
    category: "project_size",
    priority: "medium",
    question: "Which fixtures or items are involved?",
    questionType: "checkbox",
    choices: ["Toilet", "Sink or faucet", "Shower or tub", "Dishwasher", "Washing machine", "Garbage disposal", "Sump pump", "Other"],
    requiredInformation: "Specific fixtures in scope",
    tags: ["fixtures", "items"],
  },
  {
    id: "plumber_issue_description",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the main plumbing issue or goal?",
    questionType: "short_text",
    requiredInformation: "Primary plumbing problem or project goal",
    tags: ["issue", "description"],
  },
  {
    id: "plumber_active_leak",
    category: "existing_conditions",
    priority: "very_high",
    question: "Is there an active leak right now?",
    questionType: "multiple_choice",
    choices: ["Yes — urgent", "Yes — slow leak", "No active leak", "Not sure"],
    requiredInformation: "Active leak status and urgency",
    tags: ["leak", "urgent"],
  },
  {
    id: "plumber_pipe_material",
    category: "existing_conditions",
    priority: "high",
    question: "Do you know your existing pipe material?",
    questionType: "multiple_choice",
    choices: ["Copper", "PEX", "PVC / CPVC", "Galvanized", "Mixed", "Not sure"],
    requiredInformation: "Existing pipe material",
    tags: ["pipes", "material"],
  },
  {
    id: "plumber_home_age",
    category: "existing_conditions",
    priority: "high",
    question: "Approximately how old is the home?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–30 years", "30–50 years", "Over 50 years", "Not sure"],
    requiredInformation: "Home age affecting plumbing systems",
    tags: ["age", "home"],
  },
  {
    id: "plumber_drain_issue",
    category: "existing_conditions",
    priority: "high",
    question: "Are you experiencing slow or clogged drains?",
    questionType: "multiple_choice",
    choices: ["No", "One fixture", "Multiple fixtures", "Main line concern", "Not sure"],
    requiredInformation: "Drain clog scope and severity",
    tags: ["drains", "clogs"],
  },
  {
    id: "plumber_water_pressure",
    category: "existing_conditions",
    priority: "medium",
    question: "Have you noticed low water pressure?",
    questionType: "multiple_choice",
    choices: ["No issues", "One fixture", "Whole house", "Intermittent", "Not sure"],
    requiredInformation: "Water pressure issues",
    tags: ["pressure", "water"],
  },
  {
    id: "plumber_previous_repairs",
    category: "existing_conditions",
    priority: "medium",
    question: "Have there been recent plumbing repairs in this area?",
    questionType: "yes_no",
    requiredInformation: "Recent repair history in affected area",
    tags: ["history", "repairs"],
  },
  {
    id: "plumber_sewer_line",
    category: "existing_conditions",
    priority: "medium",
    question: "Is the sewer or main drain line involved?",
    questionType: "multiple_choice",
    choices: ["No", "Possible — not confirmed", "Yes — confirmed issue", "Not sure"],
    requiredInformation: "Sewer or main line involvement",
    tags: ["sewer", "main_line"],
  },
  {
    id: "plumber_fixture_supplied",
    category: "materials",
    priority: "high",
    question: "Will you supply the fixtures or should the contractor?",
    questionType: "multiple_choice",
    choices: ["I'll supply fixtures", "Contractor supplies fixtures", "Mix — some supplied by me", "Not sure yet"],
    requiredInformation: "Fixture supply responsibility",
    tags: ["fixtures", "materials"],
  },
  {
    id: "plumber_fixture_brand",
    category: "materials",
    priority: "medium",
    question: "Do you have a preferred fixture brand or style?",
    questionType: "multiple_choice",
    choices: ["Yes — specific brand", "Standard quality", "Premium quality", "Contractor to recommend", "No preference"],
    requiredInformation: "Fixture brand or quality preference",
    tags: ["brand", "fixtures"],
  },
  {
    id: "plumber_pipe_preference",
    category: "materials",
    priority: "medium",
    question: "Do you have a preference for replacement pipe material?",
    questionType: "multiple_choice",
    choices: ["PEX", "Copper", "CPVC", "Match existing", "Contractor to advise", "Not applicable"],
    requiredInformation: "Preferred replacement pipe material",
    tags: ["pipes", "material"],
  },
  {
    id: "plumber_water_heater_type",
    category: "materials",
    priority: "medium",
    question: "If replacing a water heater, what type do you prefer?",
    questionType: "multiple_choice",
    choices: ["Tank — standard", "Tankless", "Heat pump", "Keep same type", "Contractor to advise", "Not applicable"],
    requiredInformation: "Water heater type preference",
    tags: ["water_heater", "type"],
  },
  {
    id: "plumber_gas_line",
    category: "special_features",
    priority: "high",
    question: "Is gas line work involved?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — new gas line", "Yes — relocate existing", "Yes — repair", "Not sure"],
    requiredInformation: "Gas line work scope",
    tags: ["gas", "safety"],
  },
  {
    id: "plumber_backflow_prevention",
    category: "special_features",
    priority: "medium",
    question: "Is a backflow preventer or expansion tank needed?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — required", "Possibly — not sure", "Already installed"],
    requiredInformation: "Backflow or expansion tank requirements",
    tags: ["backflow", "code"],
  },
  {
    id: "plumber_rough_in",
    category: "special_features",
    priority: "medium",
    question: "Is this rough-in work for new construction or remodel?",
    questionType: "multiple_choice",
    choices: ["No — finished install only", "Yes — rough-in only", "Yes — rough-in and finish", "Not sure"],
    requiredInformation: "Rough-in vs finish plumbing scope",
    tags: ["rough_in", "remodel"],
  },
  {
    id: "plumber_permit_needed",
    category: "special_features",
    priority: "medium",
    question: "Do you expect permits to be required?",
    questionType: "multiple_choice",
    choices: ["Yes — contractor to handle", "Yes — I'll handle permits", "No permits needed", "Not sure"],
    requiredInformation: "Permit requirements and responsibility",
    tags: ["permits", "code"],
  },
  {
    id: "plumber_access_panel",
    category: "access_removal",
    priority: "high",
    question: "Is access to pipes behind walls or under floors needed?",
    questionType: "multiple_choice",
    choices: ["No — accessible", "Minor access (one area)", "Significant drywall or floor access", "Not sure"],
    requiredInformation: "Access requirements for concealed plumbing",
    tags: ["access", "walls"],
  },
  {
    id: "plumber_shutoff_location",
    category: "access_removal",
    priority: "medium",
    question: "Do you know where your main water shutoff is?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Not sure"],
    requiredInformation: "Main water shutoff accessibility",
    tags: ["shutoff", "access"],
  },
  {
    id: "plumber_crawlspace_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there crawlspace or basement access for the plumber?",
    questionType: "multiple_choice",
    choices: ["Yes — easy access", "Yes — limited access", "No access", "Not applicable"],
    requiredInformation: "Below-grade access for plumbing work",
    tags: ["crawlspace", "basement", "access"],
  },
  {
    id: "plumber_occupancy",
    category: "access_removal",
    priority: "medium",
    question: "Will water need to be shut off during the project?",
    questionType: "multiple_choice",
    choices: ["Brief shutoff only", "Extended shutoff — plan ahead", "No shutoff expected", "Not sure"],
    requiredInformation: "Water shutoff impact during work",
    tags: ["shutoff", "occupancy"],
  },
  {
    id: "plumber_urgency",
    category: "timeline",
    priority: "very_high",
    question: "How urgent is this plumbing issue?",
    questionType: "multiple_choice",
    choices: ["Emergency — need help today", "Urgent — within a few days", "Soon — within 1–2 weeks", "Can wait — flexible"],
    requiredInformation: "Issue urgency and response timeframe",
    tags: ["urgency", "timeline"],
  },
  {
    id: "plumber_preferred_schedule",
    category: "timeline",
    priority: "high",
    question: "When would you prefer the work to be done?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "This week", "Within 2 weeks", "Within 1 month", "Flexible"],
    requiredInformation: "Preferred work schedule",
    tags: ["schedule", "timeline"],
  },
  {
    id: "plumber_availability",
    category: "timeline",
    priority: "medium",
    question: "What days or times work best for a service call?",
    questionType: "multiple_choice",
    choices: ["Weekday mornings", "Weekday afternoons", "Weekends", "Any time", "Flexible"],
    requiredInformation: "Customer availability for service visits",
    tags: ["availability", "schedule"],
  },
  {
    id: "plumber_warranty_preference",
    category: "customer_preferences",
    priority: "medium",
    question: "Is a labor warranty important to you?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Labor warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "plumber_licensed_insured",
    category: "customer_preferences",
    priority: "medium",
    question: "Do you require a licensed and insured plumber?",
    questionType: "yes_no",
    requiredInformation: "Licensing and insurance requirement",
    tags: ["licensed", "insured"],
  },
  {
    id: "plumber_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other quotes for this work?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other quote", "Yes — multiple quotes", "Prefer not to say"],
    requiredInformation: "Whether customer has other quotes",
    tags: ["quotes", "comparison"],
  },
  {
    id: "plumber_maintenance_plan",
    category: "customer_preferences",
    priority: "low",
    question: "Are you interested in ongoing plumbing maintenance?",
    questionType: "yes_no",
    requiredInformation: "Interest in maintenance plans",
    tags: ["maintenance", "ongoing"],
  },
  {
    id: "plumber_water_quality",
    category: "customer_preferences",
    priority: "low",
    question: "Are you concerned about water quality (hard water, filtration)?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Hard water issues", "Want filtration system", "Already have filtration", "Not sure"],
    requiredInformation: "Water quality concerns",
    tags: ["water_quality", "filtration"],
  },
  {
    id: "plumber_code_compliance",
    category: "customer_preferences",
    priority: "low",
    question: "Is bringing plumbing up to current code a priority?",
    questionType: "multiple_choice",
    choices: ["Yes — full code compliance", "Fix the issue only", "Contractor to advise", "Not sure"],
    requiredInformation: "Code compliance priority",
    tags: ["code", "compliance"],
  },
]);
