import { defineTradeQuestions } from "../builder";

export const ROOFER_QUESTIONS = defineTradeQuestions("roofer", [
  {
    id: "roofer_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of roofing work do you need?",
    questionType: "multiple_choice",
    choices: ["Full replacement", "Partial repair", "New construction", "Re-roof over existing", "Inspection", "Gutters included"],
    requiredInformation: "Primary roofing project type",
    tags: ["scope", "type"],
  },
  {
    id: "roofer_roof_area",
    category: "project_size",
    priority: "very_high",
    question: "Approximate roof size?",
    questionType: "multiple_choice",
    choices: ["Under 1,000 sq ft", "1,000–2,000 sq ft", "2,000–3,500 sq ft", "3,500–5,000 sq ft", "Over 5,000 sq ft", "Not sure"],
    requiredInformation: "Approximate roof area",
    tags: ["size", "area"],
  },
  {
    id: "roofer_stories",
    category: "project_size",
    priority: "high",
    question: "How many stories is the roof?",
    questionType: "multiple_choice",
    choices: ["1 story", "2 stories", "3+ stories", "Split-level"],
    requiredInformation: "Roof height and story count",
    tags: ["stories", "height"],
  },
  {
    id: "roofer_roof_pitch",
    category: "project_size",
    priority: "high",
    question: "What is the roof pitch (steepness)?",
    questionType: "multiple_choice",
    choices: ["Low slope / flat", "Moderate pitch", "Steep pitch", "Mixed pitches", "Not sure"],
    requiredInformation: "Roof pitch affecting labor and safety",
    tags: ["pitch", "slope"],
  },
  {
    id: "roofer_layers",
    category: "project_size",
    priority: "medium",
    question: "How many existing roof layers are there?",
    questionType: "multiple_choice",
    choices: ["1 layer", "2 layers", "3+ layers", "Not sure"],
    requiredInformation: "Number of existing roof layers",
    tags: ["layers", "tear_off"],
  },
  {
    id: "roofer_sections",
    category: "project_size",
    priority: "medium",
    question: "Which roof sections are involved?",
    questionType: "checkbox",
    choices: ["Main roof", "Garage", "Porch / awning", "Shed", "Flat section", "All sections"],
    requiredInformation: "Roof sections in scope",
    tags: ["sections", "scope"],
  },
  {
    id: "roofer_current_material",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is your current roofing material?",
    questionType: "multiple_choice",
    choices: ["Asphalt shingles", "Metal", "Tile", "Flat / membrane", "Wood shake", "Slate", "Not sure"],
    requiredInformation: "Current roofing material",
    tags: ["material", "existing"],
  },
  {
    id: "roofer_roof_age",
    category: "existing_conditions",
    priority: "very_high",
    question: "How old is your current roof?",
    questionType: "multiple_choice",
    choices: ["Under 10 years", "10–20 years", "20–30 years", "Over 30 years", "Not sure"],
    requiredInformation: "Current roof age",
    tags: ["age", "existing"],
  },
  {
    id: "roofer_active_leak",
    category: "existing_conditions",
    priority: "very_high",
    question: "Do you have an active roof leak?",
    questionType: "multiple_choice",
    choices: ["Yes — active leak now", "Yes — leaks during heavy rain", "No active leak", "Not sure"],
    requiredInformation: "Active leak status",
    tags: ["leak", "urgent"],
  },
  {
    id: "roofer_damage_extent",
    category: "existing_conditions",
    priority: "high",
    question: "What damage is visible on the roof?",
    questionType: "checkbox",
    choices: ["Missing shingles", "Curling or buckling", "Granule loss", "Sagging", "Moss or algae", "Flashing damage", "No visible damage", "Other"],
    requiredInformation: "Visible roof damage types",
    tags: ["damage", "condition"],
  },
  {
    id: "roofer_storm_damage",
    category: "existing_conditions",
    priority: "high",
    question: "Was the damage caused by a storm or hail?",
    questionType: "multiple_choice",
    choices: ["Yes — storm damage", "Yes — hail damage", "No — age-related wear", "Not sure"],
    requiredInformation: "Storm or hail damage involvement",
    tags: ["storm", "hail", "insurance"],
  },
  {
    id: "roofer_deck_condition",
    category: "existing_conditions",
    priority: "high",
    question: "Do you know the condition of the roof deck (sheathing)?",
    questionType: "multiple_choice",
    choices: ["Good condition", "Some soft spots suspected", "Known rot or damage", "Not sure"],
    requiredInformation: "Roof deck condition",
    tags: ["deck", "sheathing"],
  },
  {
    id: "roofer_ventilation",
    category: "existing_conditions",
    priority: "medium",
    question: "Is your attic ventilation adequate?",
    questionType: "multiple_choice",
    choices: ["Yes", "No — needs improvement", "Not sure"],
    requiredInformation: "Attic ventilation status",
    tags: ["ventilation", "attic"],
  },
  {
    id: "roofer_new_material",
    category: "materials",
    priority: "high",
    question: "What roofing material do you want?",
    questionType: "multiple_choice",
    choices: ["Asphalt shingles", "Architectural shingles", "Metal", "Tile", "Flat / membrane", "Match existing", "Contractor to advise"],
    requiredInformation: "Desired new roofing material",
    tags: ["material", "preference"],
  },
  {
    id: "roofer_shingle_quality",
    category: "materials",
    priority: "medium",
    question: "What shingle quality tier do you prefer?",
    questionType: "multiple_choice",
    choices: ["Standard (3-tab)", "Architectural / dimensional", "Premium / designer", "Contractor to advise", "Not applicable"],
    requiredInformation: "Shingle quality preference",
    tags: ["shingles", "quality"],
  },
  {
    id: "roofer_underlayment",
    category: "materials",
    priority: "medium",
    question: "Do you want upgraded underlayment or ice/water shield?",
    questionType: "multiple_choice",
    choices: ["Standard underlayment", "Upgraded synthetic underlayment", "Ice and water shield in valleys/eaves", "Full ice and water shield", "Contractor to advise"],
    requiredInformation: "Underlayment and ice shield preference",
    tags: ["underlayment", "ice_shield"],
  },
  {
    id: "roofer_color_preference",
    category: "materials",
    priority: "low",
    question: "Do you have a color preference for the new roof?",
    questionType: "multiple_choice",
    choices: ["Yes — specific color", "Dark tones", "Light tones", "Match neighborhood", "No preference"],
    requiredInformation: "Roof color preference",
    tags: ["color", "aesthetics"],
  },
  {
    id: "roofer_gutters",
    category: "special_features",
    priority: "medium",
    question: "Are gutters part of this project?",
    questionType: "multiple_choice",
    choices: ["No", "Repair existing gutters", "Replace gutters", "Add new gutters", "Gutter guards"],
    requiredInformation: "Gutter work scope",
    tags: ["gutters", "drainage"],
  },
  {
    id: "roofer_skylights",
    category: "special_features",
    priority: "medium",
    question: "Are there skylights or roof windows involved?",
    questionType: "multiple_choice",
    choices: ["No skylights", "Replace existing skylights", "Add new skylights", "Seal / repair around skylights"],
    requiredInformation: "Skylight scope",
    tags: ["skylights", "windows"],
  },
  {
    id: "roofer_chimney",
    category: "special_features",
    priority: "medium",
    question: "Is chimney flashing or repair needed?",
    questionType: "multiple_choice",
    choices: ["No chimney", "Re-flash existing chimney", "Chimney repair needed", "Not sure"],
    requiredInformation: "Chimney flashing and repair scope",
    tags: ["chimney", "flashing"],
  },
  {
    id: "roofer_solar_panels",
    category: "special_features",
    priority: "low",
    question: "Are solar panels on the roof?",
    questionType: "multiple_choice",
    choices: ["No solar panels", "Yes — need removal and reinstall", "Yes — staying in place", "Planning to add solar"],
    requiredInformation: "Solar panel impact on roofing",
    tags: ["solar", "panels"],
  },
  {
    id: "roofer_tear_off",
    category: "access_removal",
    priority: "very_high",
    question: "Should the old roof be torn off completely?",
    questionType: "multiple_choice",
    choices: ["Yes — full tear-off", "No — roof over existing", "Contractor to advise", "Not sure"],
    requiredInformation: "Tear-off vs overlay preference",
    tags: ["tear_off", "removal"],
  },
  {
    id: "roofer_debris_disposal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor handle debris removal and disposal?",
    questionType: "yes_no",
    requiredInformation: "Debris removal responsibility",
    tags: ["disposal", "debris"],
  },
  {
    id: "roofer_driveway_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there driveway access for a dumpster or materials?",
    questionType: "multiple_choice",
    choices: ["Yes — ample access", "Limited access", "No driveway access", "Not sure"],
    requiredInformation: "Driveway and site access for materials",
    tags: ["access", "driveway"],
  },
  {
    id: "roofer_landscaping_protection",
    category: "access_removal",
    priority: "medium",
    question: "Are there landscaping areas that need protection?",
    questionType: "multiple_choice",
    choices: ["No concerns", "Some plants near the house", "Significant landscaping to protect", "Not sure"],
    requiredInformation: "Landscaping protection needs",
    tags: ["landscaping", "protection"],
  },
  {
    id: "roofer_urgency",
    category: "timeline",
    priority: "very_high",
    question: "How urgent is this roofing project?",
    questionType: "multiple_choice",
    choices: ["Emergency — active leak", "Urgent — before next storm", "Soon — within 1 month", "Planning ahead — flexible"],
    requiredInformation: "Project urgency",
    tags: ["urgency", "timeline"],
  },
  {
    id: "roofer_preferred_season",
    category: "timeline",
    priority: "high",
    question: "When would you like the work done?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "This season", "Next season", "Specific date", "Flexible"],
    requiredInformation: "Preferred work timeframe",
    tags: ["season", "timeline"],
  },
  {
    id: "roofer_insurance_claim",
    category: "timeline",
    priority: "medium",
    question: "Is this related to an insurance claim?",
    questionType: "multiple_choice",
    choices: ["No", "Yes — claim filed", "Yes — planning to file", "Not sure"],
    requiredInformation: "Insurance claim involvement",
    tags: ["insurance", "claim"],
  },
  {
    id: "roofer_warranty_priority",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is a manufacturer and workmanship warranty?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "roofer_ventilation_upgrade",
    category: "customer_preferences",
    priority: "medium",
    question: "Are you interested in improving attic ventilation?",
    questionType: "yes_no",
    requiredInformation: "Attic ventilation upgrade interest",
    tags: ["ventilation", "upgrade"],
  },
  {
    id: "roofer_energy_efficiency",
    category: "customer_preferences",
    priority: "low",
    question: "Are cool roof or energy-efficient options important?",
    questionType: "multiple_choice",
    choices: ["Yes — energy efficiency priority", "Somewhat interested", "Not a priority"],
    requiredInformation: "Energy-efficient roofing interest",
    tags: ["energy", "cool_roof"],
  },
  {
    id: "roofer_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other roofing quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "roofer_occupancy",
    category: "customer_preferences",
    priority: "low",
    question: "Will you be living in the home during the roof work?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during roofing project",
    tags: ["occupied", "living"],
  },
  {
    id: "roofer_permit",
    category: "customer_preferences",
    priority: "low",
    question: "Should the contractor handle permits?",
    questionType: "multiple_choice",
    choices: ["Yes", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling preference",
    tags: ["permits"],
  },
  {
    id: "roofer_inspection_report",
    category: "customer_preferences",
    priority: "low",
    question: "Do you have a recent roof inspection report?",
    questionType: "yes_no",
    requiredInformation: "Existing inspection report availability",
    tags: ["inspection", "report"],
  },
]);
