import { defineTradeQuestions } from "../builder";

export const WINDOWS_DOORS_QUESTIONS = defineTradeQuestions("windows_doors", [
  {
    id: "windows_doors_project_type",
    category: "project_size",
    priority: "very_high",
    question: "What type of project is this?",
    questionType: "multiple_choice",
    choices: ["Window replacement", "Door replacement", "Both windows and doors", "New installation", "Repair only"],
    requiredInformation: "Primary windows and doors project type",
    tags: ["scope", "type"],
  },
  {
    id: "windows_doors_window_count",
    category: "project_size",
    priority: "very_high",
    question: "How many windows are involved?",
    questionType: "multiple_choice",
    choices: ["1–3", "4–8", "9–15", "16–25", "26+", "No windows — doors only"],
    requiredInformation: "Number of windows in scope",
    tags: ["windows", "count"],
  },
  {
    id: "windows_doors_door_count",
    category: "project_size",
    priority: "very_high",
    question: "How many doors are involved?",
    questionType: "multiple_choice",
    choices: ["1", "2–3", "4–6", "7+", "No doors — windows only"],
    requiredInformation: "Number of doors in scope",
    tags: ["doors", "count"],
  },
  {
    id: "windows_doors_door_types",
    category: "project_size",
    priority: "high",
    question: "Which door types are included?",
    questionType: "checkbox",
    choices: ["Entry / front door", "Sliding patio door", "French doors", "Garage entry", "Interior doors", "Storm door", "Other"],
    requiredInformation: "Door types in scope",
    tags: ["doors", "types"],
  },
  {
    id: "windows_doors_stories",
    category: "project_size",
    priority: "high",
    question: "How many stories have windows to replace?",
    questionType: "multiple_choice",
    choices: ["1 story", "2 stories", "3+ stories", "Not applicable"],
    requiredInformation: "Number of stories for window work",
    tags: ["stories", "access"],
  },
  {
    id: "windows_doors_whole_home",
    category: "project_size",
    priority: "medium",
    question: "Is this a whole-home replacement or partial?",
    questionType: "multiple_choice",
    choices: ["Whole home", "Front of home only", "Specific rooms", "Single unit only"],
    requiredInformation: "Whole-home vs partial replacement",
    tags: ["scope", "partial"],
  },
  {
    id: "windows_doors_current_type",
    category: "existing_conditions",
    priority: "very_high",
    question: "What type of windows do you currently have?",
    questionType: "multiple_choice",
    choices: ["Single-pane", "Double-pane", "Triple-pane", "Mixed types", "Not sure"],
    requiredInformation: "Current window type",
    tags: ["windows", "existing"],
  },
  {
    id: "windows_doors_current_condition",
    category: "existing_conditions",
    priority: "very_high",
    question: "What is the condition of existing windows or doors?",
    questionType: "multiple_choice",
    choices: ["Good — upgrading for efficiency", "Fair — some issues", "Poor — drafts, fogging, or damage", "Not sure"],
    requiredInformation: "Current window and door condition",
    tags: ["condition", "existing"],
  },
  {
    id: "windows_doors_frame_material",
    category: "existing_conditions",
    priority: "high",
    question: "What material are current window frames?",
    questionType: "multiple_choice",
    choices: ["Wood", "Vinyl", "Aluminum", "Fiberglass", "Mixed", "Not sure"],
    requiredInformation: "Existing window frame material",
    tags: ["frames", "material"],
  },
  {
    id: "windows_doors_rot_damage",
    category: "existing_conditions",
    priority: "high",
    question: "Is there rot or water damage around frames or sills?",
    questionType: "multiple_choice",
    choices: ["No damage", "Minor damage", "Moderate damage", "Significant damage", "Not sure"],
    requiredInformation: "Rot and water damage around openings",
    tags: ["rot", "water_damage"],
  },
  {
    id: "windows_doors_opening_size",
    category: "existing_conditions",
    priority: "medium",
    question: "Are you changing any opening sizes?",
    questionType: "multiple_choice",
    choices: ["No — same size replacements", "Enlarge some openings", "Reduce some openings", "Add new openings", "Not sure"],
    requiredInformation: "Opening size changes",
    tags: ["openings", "size"],
  },
  {
    id: "windows_doors_home_age",
    category: "existing_conditions",
    priority: "medium",
    question: "Approximately how old is the home?",
    questionType: "multiple_choice",
    choices: ["Under 15 years", "15–30 years", "30–50 years", "Over 50 years", "Not sure"],
    requiredInformation: "Home age affecting window and door fit",
    tags: ["age", "home"],
  },
  {
    id: "windows_doors_window_material",
    category: "materials",
    priority: "high",
    question: "What window frame material do you prefer?",
    questionType: "multiple_choice",
    choices: ["Vinyl", "Wood", "Fiberglass", "Aluminum", "Clad wood", "Contractor to advise", "Not sure"],
    requiredInformation: "Preferred window frame material",
    tags: ["windows", "material"],
  },
  {
    id: "windows_doors_glass_type",
    category: "materials",
    priority: "medium",
    question: "What glass package do you want?",
    questionType: "multiple_choice",
    choices: ["Standard double-pane", "Low-E coating", "Triple-pane", "Impact-rated", "Contractor to advise", "Not sure"],
    requiredInformation: "Glass package preference",
    tags: ["glass", "efficiency"],
  },
  {
    id: "windows_doors_door_material",
    category: "materials",
    priority: "high",
    question: "What door material do you prefer?",
    questionType: "multiple_choice",
    choices: ["Fiberglass", "Steel", "Wood", "Aluminum", "Vinyl (sliding)", "Contractor to advise", "Not applicable"],
    requiredInformation: "Preferred door material",
    tags: ["doors", "material"],
  },
  {
    id: "windows_doors_style",
    category: "materials",
    priority: "medium",
    question: "What window style do you prefer?",
    questionType: "multiple_choice",
    choices: ["Double-hung", "Casement", "Sliding", "Picture / fixed", "Bay or bow", "Match existing", "Not sure"],
    requiredInformation: "Window style preference",
    tags: ["style", "windows"],
  },
  {
    id: "windows_doors_color",
    category: "materials",
    priority: "low",
    question: "Do you have a color preference for frames or doors?",
    questionType: "multiple_choice",
    choices: ["White", "Black", "Wood grain", "Custom color", "Match existing", "No preference"],
    requiredInformation: "Frame and door color preference",
    tags: ["color", "aesthetics"],
  },
  {
    id: "windows_doors_grilles",
    category: "special_features",
    priority: "low",
    question: "Do you want decorative grilles or grids?",
    questionType: "multiple_choice",
    choices: ["No grilles", "Between-glass grilles", "Simulated divided lites", "True divided lites", "Not sure"],
    requiredInformation: "Grille or grid preference",
    tags: ["grilles", "aesthetics"],
  },
  {
    id: "windows_doors_security",
    category: "special_features",
    priority: "medium",
    question: "Are security features important?",
    questionType: "multiple_choice",
    choices: ["Standard locks", "Upgraded locks and hardware", "Impact-rated glass", "Security screen door", "Not a priority"],
    requiredInformation: "Security feature requirements",
    tags: ["security", "locks"],
  },
  {
    id: "windows_doors_blinds",
    category: "special_features",
    priority: "low",
    question: "Do you want built-in blinds or shades?",
    questionType: "multiple_choice",
    choices: ["No", "Between-glass blinds", "Motorized shades", "Not sure"],
    requiredInformation: "Built-in blinds or shades interest",
    tags: ["blinds", "shades"],
  },
  {
    id: "windows_doors_trim",
    category: "special_features",
    priority: "medium",
    question: "Is interior or exterior trim part of this project?",
    questionType: "multiple_choice",
    choices: ["No trim work", "Interior trim only", "Exterior trim only", "Both interior and exterior", "Not sure"],
    requiredInformation: "Trim work scope",
    tags: ["trim", "casing"],
  },
  {
    id: "windows_doors_install_type",
    category: "access_removal",
    priority: "very_high",
    question: "What type of installation do you need?",
    questionType: "multiple_choice",
    choices: ["Insert / retrofit", "Full frame replacement", "New construction", "Not sure"],
    requiredInformation: "Installation type — insert vs full frame",
    tags: ["installation", "type"],
  },
  {
    id: "windows_doors_removal_disposal",
    category: "access_removal",
    priority: "high",
    question: "Should the contractor remove and dispose of old units?",
    questionType: "yes_no",
    requiredInformation: "Old window and door removal responsibility",
    tags: ["removal", "disposal"],
  },
  {
    id: "windows_doors_interior_finish",
    category: "access_removal",
    priority: "medium",
    question: "Will interior finishing (drywall, paint) be needed?",
    questionType: "multiple_choice",
    choices: ["No finishing needed", "Minor touch-up", "Significant finishing work", "Contractor handles all finishing", "Not sure"],
    requiredInformation: "Interior finishing scope after install",
    tags: ["finishing", "drywall"],
  },
  {
    id: "windows_doors_access",
    category: "access_removal",
    priority: "medium",
    question: "Is there clear access to all windows and doors?",
    questionType: "multiple_choice",
    choices: ["Yes — easy access", "Some landscaping or obstacles", "Difficult access — scaffolding needed", "Not sure"],
    requiredInformation: "Site access for installation",
    tags: ["access", "scaffolding"],
  },
  {
    id: "windows_doors_start_date",
    category: "timeline",
    priority: "high",
    question: "When would you like installation to begin?",
    questionType: "multiple_choice",
    choices: ["As soon as possible", "Within 2 weeks", "Within 1 month", "Within 2–3 months", "Flexible"],
    requiredInformation: "Desired installation start date",
    tags: ["timeline", "start"],
  },
  {
    id: "windows_doors_lead_time",
    category: "timeline",
    priority: "medium",
    question: "Are you aware that custom orders may have lead times?",
    questionType: "multiple_choice",
    choices: ["Yes — flexible on timing", "Need fastest available", "Have a hard deadline", "Not sure"],
    requiredInformation: "Lead time flexibility",
    tags: ["lead_time", "timeline"],
  },
  {
    id: "windows_doors_energy_efficiency",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is energy efficiency?",
    questionType: "multiple_choice",
    choices: ["Top priority", "Important", "Moderate", "Not a concern"],
    requiredInformation: "Energy efficiency priority",
    tags: ["energy", "efficiency"],
  },
  {
    id: "windows_doors_noise_reduction",
    category: "customer_preferences",
    priority: "low",
    question: "Is noise reduction important?",
    questionType: "multiple_choice",
    choices: ["Yes — near busy road or airport", "Somewhat", "Not a concern"],
    requiredInformation: "Noise reduction priority",
    tags: ["noise", "sound"],
  },
  {
    id: "windows_doors_warranty",
    category: "customer_preferences",
    priority: "medium",
    question: "How important is a manufacturer and installation warranty?",
    questionType: "multiple_choice",
    choices: ["Very important", "Nice to have", "Not a priority"],
    requiredInformation: "Warranty priority",
    tags: ["warranty", "preferences"],
  },
  {
    id: "windows_doors_previous_quotes",
    category: "customer_preferences",
    priority: "low",
    question: "Have you received other window or door quotes?",
    questionType: "multiple_choice",
    choices: ["No — first quote", "Yes — 1 other", "Yes — multiple", "Prefer not to say"],
    requiredInformation: "Other quote status",
    tags: ["quotes", "comparison"],
  },
  {
    id: "windows_doors_permits",
    category: "customer_preferences",
    priority: "low",
    question: "Should the contractor handle permits?",
    questionType: "multiple_choice",
    choices: ["Yes", "I'll handle permits", "Not sure if needed"],
    requiredInformation: "Permit handling preference",
    tags: ["permits"],
  },
  {
    id: "windows_doors_occupied",
    category: "customer_preferences",
    priority: "low",
    question: "Will you be home during installation?",
    questionType: "yes_no",
    requiredInformation: "Occupancy during installation",
    tags: ["occupied", "access"],
  },
  {
    id: "windows_doors_supply",
    category: "materials",
    priority: "medium",
    question: "Will you supply the windows or doors?",
    questionType: "multiple_choice",
    choices: ["Contractor supplies all", "I'll supply units — install only", "Not sure"],
    requiredInformation: "Product supply responsibility",
    tags: ["supply", "materials"],
  },
  {
    id: "windows_doors_historic",
    category: "existing_conditions",
    priority: "low",
    question: "Is the home in a historic district with restrictions?",
    questionType: "multiple_choice",
    choices: ["No restrictions", "Yes — historic district", "HOA restrictions", "Not sure"],
    requiredInformation: "Historic or HOA restrictions on windows",
    tags: ["historic", "hoa"],
  },
]);
