import type { LibraryQuestion } from "@/lib/quote-requests/question-library/types";

/** Exterior grading / drainage / water pooling near foundation */
export const EXTERIOR_DRAINAGE_QUESTIONS: LibraryQuestion[] = [
  {
    id: "specialty_ed_water_location",
    trade: "specialty",
    category: "existing_conditions",
    priority: "very_high",
    question: "Where does water accumulate near your home?",
    questionType: "multiple_choice",
    choices: [
      "Along one side of the foundation",
      "Around the entire foundation",
      "Near downspouts",
      "In the yard away from the house",
      "Not sure",
    ],
    requiredInformation: "Where exterior water pools",
    tags: ["drainage", "water", "foundation"],
  },
  {
    id: "specialty_ed_slope_toward_house",
    trade: "specialty",
    category: "existing_conditions",
    priority: "very_high",
    question: "Does the ground slope toward the foundation in that area?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Not sure"],
    requiredInformation: "Whether grading slopes toward the house",
    tags: ["grading", "slope", "drainage"],
  },
  {
    id: "specialty_ed_downspouts",
    trade: "specialty",
    category: "existing_conditions",
    priority: "high",
    question: "Do downspouts discharge near the foundation?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Some do", "Not sure"],
    requiredInformation: "Downspout discharge near foundation",
    tags: ["downspout", "drainage"],
  },
  {
    id: "specialty_ed_frequency",
    trade: "specialty",
    category: "existing_conditions",
    priority: "high",
    question: "How often does water pool during rain?",
    questionType: "multiple_choice",
    choices: [
      "Every heavy rain",
      "Occasionally",
      "Only after prolonged rain",
      "Rarely",
      "Not sure",
    ],
    requiredInformation: "How frequently exterior water pooling occurs",
    tags: ["drainage", "rain"],
  },
  {
    id: "specialty_ed_service_type",
    trade: "specialty",
    category: "materials",
    priority: "high",
    question:
      "What kind of help are you looking for?",
    questionType: "multiple_choice",
    choices: [
      "Grading / re-sloping",
      "Exterior drainage (swale, French drain, etc.)",
      "Exterior waterproofing",
      "Not sure",
    ],
    requiredInformation: "Exterior water management service type",
    tags: ["grading", "drainage", "waterproofing"],
  },
  {
    id: "specialty_ed_exterior_access",
    trade: "specialty",
    category: "access_removal",
    priority: "medium",
    question: "Is there clear access to the exterior foundation wall for work?",
    questionType: "yes_no",
    requiredInformation: "Exterior access for grading or drainage work",
    tags: ["access", "exterior"],
  },
];
