import type { LibraryQuestion } from "@/lib/quote-requests/question-library/types";

/** Foundation / basement leak / waterproofing specialty question set */
export const FOUNDATION_WATERPROOFING_QUESTIONS: LibraryQuestion[] = [
  {
    id: "specialty_fw_active_leak",
    trade: "specialty",
    category: "existing_conditions",
    priority: "very_high",
    question: "Is there any standing water or active leaking right now?",
    questionType: "multiple_choice",
    choices: [
      "Yes",
      "No",
      "Not right now, but it has leaked before",
    ],
    requiredInformation: "Whether water is actively entering the basement",
    tags: ["leak", "urgent", "water", "active"],
  },
  {
    id: "specialty_fw_water_entry_point",
    trade: "specialty",
    category: "existing_conditions",
    priority: "very_high",
    question: "Where is the water coming in?",
    questionType: "multiple_choice",
    choices: [
      "Through a visible foundation crack",
      "Around a window",
      "Through the floor/wall joint",
      "Through the floor",
      "Not sure",
    ],
    requiredInformation: "Water entry location in the basement",
    tags: ["water", "entry", "crack", "basement"],
  },
  {
    id: "specialty_fw_leak_timing",
    trade: "specialty",
    category: "existing_conditions",
    priority: "very_high",
    question: "When does the leak happen?",
    questionType: "multiple_choice",
    choices: [
      "During heavy rain",
      "After snow melts",
      "Constantly",
      "Only occasionally",
      "Not sure",
    ],
    requiredInformation: "When water intrusion occurs",
    tags: ["leak", "timing", "rain"],
  },
  {
    id: "specialty_fw_crack_visible_inside",
    trade: "specialty",
    category: "existing_conditions",
    priority: "high",
    question: "Is the crack visible from inside the basement?",
    questionType: "multiple_choice",
    choices: ["Yes", "No", "Not sure"],
    requiredInformation: "Whether foundation crack is visible from interior",
    tags: ["crack", "foundation", "basement"],
  },
  {
    id: "specialty_fw_basement_finished",
    trade: "specialty",
    category: "existing_conditions",
    priority: "high",
    question: "Is the basement finished?",
    questionType: "multiple_choice",
    choices: ["Finished", "Partially finished", "Unfinished"],
    requiredInformation: "Basement finish level for repair access",
    tags: ["basement", "finished"],
  },
  {
    id: "specialty_fw_repair_type",
    trade: "specialty",
    category: "materials",
    priority: "high",
    question:
      "Are you looking for an interior repair, exterior waterproofing, or not sure?",
    questionType: "multiple_choice",
    choices: [
      "Interior crack repair",
      "Exterior waterproofing",
      "Drainage/grading help",
      "Not sure",
    ],
    requiredInformation: "Preferred repair approach",
    tags: ["repair", "waterproofing", "interior", "exterior"],
  },
  {
    id: "specialty_fw_basement_access",
    trade: "specialty",
    category: "access_removal",
    priority: "medium",
    question: "Is the affected area accessible from inside the basement?",
    questionType: "yes_no",
    requiredInformation: "Interior basement access to the leak area",
    tags: ["access", "basement"],
  },
  {
    id: "specialty_fw_exterior_access",
    trade: "specialty",
    category: "access_removal",
    priority: "medium",
    question: "Is there clear access to the exterior foundation wall on that side?",
    questionType: "yes_no",
    requiredInformation: "Exterior foundation wall access",
    tags: ["access", "exterior", "foundation"],
  },
];
