import type { QuoteBuilderContext } from "@/lib/quote-requests/quote-builder/context";
import { siteVisitSectionObservations } from "@/lib/quote-requests/quote-builder/load-context";
import {
  emptyPricingContent,
  QUOTE_BUILDER_SECTION_LABELS,
  QUOTE_BUILDER_SECTION_ORDER,
  type QuoteBuilderSectionDraft,
  type QuoteBuilderSectionKey,
} from "@/lib/quote-requests/quote-builder/types";

function listDraft(
  key: QuoteBuilderSectionKey,
  items: string[]
): QuoteBuilderSectionDraft {
  return {
    sectionKey: key,
    title: QUOTE_BUILDER_SECTION_LABELS[key],
    content: { version: 1, items: items.filter(Boolean) },
    displayOrder: QUOTE_BUILDER_SECTION_ORDER[key],
  };
}

export function buildFallbackQuoteBuilderDraft(
  context: QuoteBuilderContext
): QuoteBuilderSectionDraft[] {
  const summary: string[] = [];
  summary.push(`${context.projectType} for ${context.customerName} at ${context.propertyAddress}.`);
  if (context.projectBrief?.overview.length) {
    summary.push(...context.projectBrief.overview.map((s) => s.text));
  } else {
    summary.push(context.description.trim());
  }
  if (context.isUrgent) summary.push("Customer indicated this project is urgent.");

  const scope: string[] = [];
  if (context.workComponents?.length) {
    for (const wc of context.workComponents) {
      scope.push(`${wc.label}: work to be completed per site conditions and customer requirements.`);
    }
  } else {
    scope.push(`Complete ${context.projectType.toLowerCase()} work as described in the customer request.`);
  }
  const siteMeasurements = siteVisitSectionObservations(context, "measurements");
  const siteConditions = siteVisitSectionObservations(context, "existing_conditions");
  const siteMaterials = siteVisitSectionObservations(context, "materials");
  if (siteConditions.length) {
    scope.push("Preparation and installation accounting for observed existing conditions.");
  }
  if (siteMeasurements.length) {
    scope.push("Work sized to confirmed or noted measurements from site visit.");
  }

  const included: string[] = [
    "Labour for described scope of work",
    "Standard jobsite cleanup of work area",
    "Disposal of project-related debris generated by our work",
  ];
  if (context.photoCount > 0) included.push("Review of customer-provided photos as part of planning");

  const confirmation: string[] = [];
  if (context.projectBrief?.itemsToVerify.length) {
    confirmation.push(...context.projectBrief.itemsToVerify.map((s) => s.text));
  }
  if (!siteMeasurements.length) {
    confirmation.push("Final measurements to be confirmed on site or from customer");
  }
  if (!siteMaterials.length) {
    confirmation.push("Material selections and finishes to be confirmed with customer");
  }
  confirmation.push("Permit requirements to be verified for this scope and municipality");
  if (context.scopeFit === "mixed_scope" || context.scopeFit === "possibly_out_of_scope") {
    confirmation.push(context.scopeReason ?? "Scope boundaries to be confirmed with customer");
  }

  const upgrades: string[] = [];
  if (context.pricingProfile === "premium") {
    upgrades.push("Premium material upgrades — pricing available upon selection");
  }
  const customerRequests = siteVisitSectionObservations(context, "customer_requests");
  if (customerRequests.length > 1) {
    upgrades.push("Additional options discussed on site — quote separately upon approval");
  }

  const exclusions: string[] = [
    "Hidden structural damage, rot, or hazardous materials not visible during site review",
    "Permit and inspection fees unless explicitly included",
    "Engineering or design services unless specified",
    "Utility relocation or work by other trades not listed in scope",
    "Changes requested by customer after quote approval",
  ];

  let timelineText = "Timeline to be confirmed after site visit.";
  if (context.isUrgent) {
    timelineText = "Expedited scheduling to be discussed with customer after quote approval.";
  } else if (siteVisitSectionObservations(context, "access").length) {
    timelineText =
      "Schedule to account for site access requirements noted during visit. Exact dates to be confirmed.";
  }

  const warrantyItems: string[] = [];
  if (context.defaultWarrantyNote?.trim()) {
    warrantyItems.push(context.defaultWarrantyNote.trim());
  } else if (context.primaryTrade) {
    warrantyItems.push(
      `Standard workmanship warranty for ${context.primaryTrade.toLowerCase()} work — terms to be finalized in writing.`
    );
  } else {
    warrantyItems.push("Standard workmanship warranty — terms to be finalized in writing.");
  }

  const assumptions: string[] = [
    "Customer provides timely access to the property",
    "Work area is safe and ready unless otherwise noted",
  ];
  const access = siteVisitSectionObservations(context, "access");
  const utilities = siteVisitSectionObservations(context, "utilities");
  if (access.length) assumptions.push(...access.map((a) => `Access: ${a}`));
  if (utilities.length) assumptions.push(...utilities.map((u) => `Utilities: ${u}`));
  if (context.projectBrief?.potentialRisks.length) {
    assumptions.push(
      ...context.projectBrief.potentialRisks.map((r) => `Risk noted: ${r.text}`)
    );
  }

  const nextSteps: string[] = [
    "Review and complete pricing below",
    "Confirm open items with customer if needed",
    "Send quote for customer approval",
  ];
  if (context.projectBrief?.recommendedNextStep) {
    nextSteps.unshift(context.projectBrief.recommendedNextStep.text);
  }

  if (context.siteVisitHasCustomerChanges) {
    scope.unshift(
      "Scope updated to reflect customer changes discussed during the site visit."
    );
  }

  const drafts: QuoteBuilderSectionDraft[] = [
    listDraft("project_summary", summary),
    listDraft("scope_of_work", scope),
    listDraft("included_work", included),
    listDraft("items_requiring_confirmation", confirmation),
    listDraft("optional_upgrades", upgrades),
    listDraft("exclusions", exclusions),
    {
      sectionKey: "suggested_timeline",
      title: QUOTE_BUILDER_SECTION_LABELS.suggested_timeline,
      content: { version: 1, text: timelineText },
      displayOrder: QUOTE_BUILDER_SECTION_ORDER.suggested_timeline,
    },
    listDraft("suggested_warranty", warrantyItems),
    listDraft("assumptions", assumptions),
    listDraft("recommended_next_steps", nextSteps),
    {
      sectionKey: "pricing",
      title: QUOTE_BUILDER_SECTION_LABELS.pricing,
      content: emptyPricingContent(),
      displayOrder: QUOTE_BUILDER_SECTION_ORDER.pricing,
    },
  ];

  return drafts;
}
